// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "title": z.string().min(2),
  "description": z.string().optional(),
  "questions": z.array(z.object({
      "id": z.string().min(1),
      "label": z.string().min(2),
      "type": z.enum(["text", "textarea", "email", "phone", "number", "select", "multi-select", "rating", "date"] as const),
      "required": z.boolean().optional(),
      "helper": z.string().optional(),
      "options": z.array(z.string()).optional()
    })).min(3).max(8),
  "completion_headline": z.string().min(2),
  "completion_message": z.string().optional()
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "intake",
  version: "1.0.0",
  surface: "intake" as const,
  sectionType: "intake" as const,
  description: `The intake form (the lead-capture page at /intake). Title, description, and the questions visitors answer. Per-vertical — a barbershop intake is short, a legal intake is structured, a coaching intake is exploratory.`,
} as const;
