import type { Guide } from "./types";

export const guide: Guide = {
  slug: "how-to-start-an-ai-automation-agency",
  title: "How to Start an AI Automation Agency (The Operator's Version, Not the Dream)",
  description:
    "Most \"how to start an AI automation agency\" content sells a dream. Here's the sober version: what you actually sell, how to pick a vertical, the delivery stack decision, real margin math, and the failure modes that kill agencies.",
  targetKeyword: "how to start an ai automation agency",
  intent: "commercial",
  cluster: "sell-agents",
  relatedTool: "/tools/agency-margin-calculator",
  relatedBest: "/agencies",
  dek: "Search \"how to start an AI automation agency\" and you'll mostly find course funnels selling a dream — screenshots of income, a promise that a handful of Zapier flows makes you rich. Strip that away and there's a real, buildable business underneath. Here's the operator's version: what you actually sell, how to pick a lane, the delivery decision, the margin math, and the ways this fails.",
  sections: [
    {
      h2: "What an AI automation agency actually sells in 2026",
      body: "The phrase \"AI automation\" gets used for two very different businesses. One is a project shop that wires up a handful of Zapier or Make flows for a client, invoices once, and moves to the next lead. The other is an operated outcome: a front office that behaves as if it's staffed — calls get answered, leads get followed up within minutes instead of days, appointments get booked, reviews get requested after the job — and the agency keeps that running, month over month, for a flat retainer. The first is a one-off gig. The second is a business with recurring revenue, and it's the one worth building toward.\n\nThe distinction matters because it changes what you're actually selling a client. Nobody wakes up wanting \"automations\"; they want fewer missed calls, faster follow-up, and a calendar that fills itself. An agent stack is the mechanism, not the pitch. If you sell the mechanism, you compete on price with every other person who watched the same YouTube tutorial. If you sell the outcome and stay accountable for it after go-live, you're selling something closer to a fractional employee — and that's a retainer, not a project fee.\n\nThis is also why \"build and leave\" agencies tend to plateau. A one-time build has a ceiling: you can only sell so many new builds per month before you run out of hours or leads. An operate-and-retain model compounds — each client you keep adds recurring revenue on top of the last, and your job shifts from constant new-client acquisition to a mix of acquisition and retention. It's a slower start and a much better twelve months in.",
    },
    {
      h2: "Pick a vertical and one offer",
      body: "\"AI for any business\" agencies tend to stall at a handful of clients and stay there. The reason isn't a lack of demand — it's that every new client is a fresh discovery process: different terminology, different objections, different intake questions, a configuration built from scratch each time. There's no compounding. A vertical-specific agency — say, one that only serves HVAC companies, or only dental practices, or only local law firms — reuses almost everything: the same intake questions, the same objection handling, the same proof points, often close to the same configuration with small edits. The tenth client in a vertical takes a fraction of the time the first one did.\n\nVertical focus also compounds on the demand side in a way \"general AI agency\" never does. Trades talk to each other — a plumber who sees his competitor's phone getting answered after-hours by an AI agent, and finds out that agent is why the competitor stopped losing weekend calls, is a warmer lead than any cold outreach you could run. Referenceable results inside a trade travel by word of mouth in a way generic case studies don't.\n\nHow to pick: a trade you already have some relationship with or genuine understanding of (you don't need to have worked in it, but you should be able to talk to an owner without sounding like a stranger), a high enough average job value that a missed call is a real cost worth solving (a missed $50 order is a different problem than a missed $8,000 roof job), and phone-driven demand — businesses where customers still call to book, rather than self-serve online, are the ones where an always-answering front office visibly changes outcomes.",
    },
    {
      h2: "The delivery stack decision",
      body: "Once you know who you're serving, you have to decide how you're going to build and run the actual system. Broadly there are two paths. The first is assembling it yourself: open-source agent frameworks, MCP servers wired to each client's calendar and CRM, and your own hosting. This gives you full control over every piece and no platform fee, but it also means you own every piece of maintenance — API changes, uptime, security patches, and the fact that ten clients on hand-built infrastructure is ten things that can each break independently. Some agency owners genuinely want this level of control, and for them it's the right call, especially early when volume is low and time is more available than cash.\n\nThe second path is a white-label platform that has already solved the plumbing: hosting, the CRM, the calendar, the client portal, and the agent-building layer, so your time goes into client configuration and relationship management instead of infrastructure. The honest trade-off is a recurring platform fee and less low-level control than a from-scratch build. Neither path is categorically better — a DIY build makes more sense for someone who wants to own the stack and has the time to maintain it; a platform makes more sense for someone whose bottleneck is client acquisition and delivery speed, not infrastructure.\n\nDisclosure, since this is where we have a stake: SeldonFrame is one of the platforms in the second category, and we build it, so weigh this paragraph accordingly. What it does concretely is give each client a whitelabel front office under your agency's own brand — an agent, a CRM, a booking calendar, and a client portal — for $29/mo flat per workspace with unlimited workspaces, no metered software fee stacked on top. It's BYOK (bring your own API key for the underlying model), which is the mechanism that keeps the software cost near zero regardless of how many clients you run — you pay the model provider directly for usage, not a markup through us. That's a genuine structural difference from tools that charge per seat or per automation, but it's still a monthly line item you should put into the margin math in the next section before deciding.",
    },
    {
      h2: "The margin math shape",
      body: "The reason this business can have real margin isn't magic — it's that once an offer is repeatable, the marginal cost of the tenth client is close to the marginal cost of the third. A client typically pays a flat monthly retainer for the operated front office. What it costs you to deliver breaks into three pieces: the platform or infrastructure fee (flat, whether you're on a white-label platform or your own hosting), the underlying model usage cost (which scales with conversation volume but, for most local-service call volumes, is a small fraction of the retainer if you're on a BYOK or usage-priced model), and your own operating time — onboarding, monthly check-ins, tuning the agent's answers as the client's business changes.\n\nThe number that actually determines whether this is a good business is how much of that third cost — your time — shrinks as you add clients. If every client needs a bespoke, from-scratch build, your time cost stays roughly constant per client and margin never really improves; you've built a job, not a business. If onboarding is repeatable — the same intake flow, the same starting configuration for the vertical, small edits per client — your time cost per client drops sharply after the first few, and that's where the retainer starts looking like real margin instead of break-even hourly work. For context on what a conventional agency software stack costs before you even add a model bill: GoHighLevel, one of the more common all-in-one platforms agencies build on, lists a starter plan around $97/month for a handful of client accounts and a top plan around $297/month for unlimited accounts as of this writing — worth knowing as a reference point regardless of which platform you choose, since it's the number most competing agencies are already paying against.\n\nRun your own numbers before committing to a retainer price — the shape above is directional, not a guarantee, and it depends heavily on your vertical's typical job value and your own delivery speed. The agency margin calculator walks through the actual line items (retainer price, platform cost, estimated usage, your time per client) so you can see where your specific offer lands before you quote a client.",
    },
    {
      h2: "Getting the first five clients",
      body: "The first clients almost never come from paid ads, and trying to buy them before your offer converts on warm intros is a common way to burn cash proving nothing. Start with your own network inside the vertical you picked — even a loose connection (a family member's contractor, a friend of a friend who runs a shop) is worth a conversation before any cold outreach. The pitch that works best in this category isn't a slide deck; it's a live demonstration on their own business. Call their listed number after hours or during a busy period, let it go to voicemail or ring out, and show them exactly what that missed call costs — then show them the same call handled by an agent. Nothing sells \"missed calls are costing you money\" like hearing your own business fail to answer.\n\nLocal business associations, trade groups, and chamber-of-commerce-style meetups are underused for this category specifically because they're unglamorous, which is exactly why they still work — you're talking to real owners in your vertical, not a cold list. Once you land one client who gets real, visible results (faster response times, more booked jobs, fewer missed calls), turn that relationship into a documented case study with their permission — specific numbers where you can honestly report them, their own words about what changed. One well-documented lighthouse client, referenced honestly, does more for the next five deals than any amount of generic marketing copy.\n\nResist paid acquisition until you have an offer that reliably converts warm intros — if you can't close someone who already trusts you and already needs the thing, paying to put the same offer in front of strangers won't fix the offer, it'll just make the failure more expensive.",
    },
    {
      h2: "The agency graveyard: how these actually fail",
      body: "A handful of failure modes account for most AI automation agencies that quietly shut down within a year. The first is selling one-off builds with no retainer attached — you get paid once, the relationship ends at go-live, and you're permanently trading time for a single invoice instead of building anything that compounds. The second is tool-stacking: layering a separate paid tool for every new capability a client asks for until the monthly software bill eats the margin you were counting on — what's sometimes called the \"tool tax,\" and it's most dangerous when nobody's tracking the running total against what each client actually pays.\n\nThe third failure mode is a trust failure, and it's the one that ends client relationships the fastest: promising full autonomy — \"the AI handles everything\" — and then losing the client's confidence the first time the agent gives a wrong answer or invents a detail it shouldn't have. This is why guardrails, a read-back or confirmation step before anything gets sent or booked, and some form of ongoing evaluation of the agent's answers aren't nice-to-haves; they're the difference between a client who forgives one bad interaction because the system caught it and a client who cancels because it didn't. Sell what the system actually does, not what you hope it will do.\n\nThe fourth is scaling client count before delivery is actually repeatable — taking on client six and seven while client one through five each still need hands-on, bespoke attention. That's the moment the margin math from the section above quietly inverts: more clients means more hours, not more leverage. Get one client's onboarding and ongoing delivery to a genuinely repeatable state — the same steps, roughly the same time, predictable results — before you go looking for the next one.",
    },
  ],
  faq: [
    {
      q: "How much does it cost to start an AI automation agency?",
      a: "It depends almost entirely on which delivery path you choose (see the delivery stack section). A DIY build on open-source tooling can start near-zero in software cost but costs real time to assemble and maintain. A white-label platform adds a flat monthly fee — ours is $29/mo per workspace, unlimited workspaces, no trial required to start using it — plus whatever the underlying model usage costs, which is typically small at local-service call volumes. Either way, budget for your own time before your first paying client, not just software.",
    },
    {
      q: "Do I need to know how to code?",
      a: "Not necessarily, especially on a white-label platform designed for configuration rather than custom development. A DIY build using open MCP servers and agent frameworks leans more technical, though the Model Context Protocol was specifically designed to reduce the amount of custom integration code needed per tool. Either way, expect real configuration work — coding or not — particularly around getting a client's calendar, CRM, and phone number correctly connected.",
    },
    {
      q: "How many clients can one person actually operate?",
      a: "There's no fixed number — it depends entirely on how repeatable your onboarding and ongoing delivery are for your chosen vertical. An agency doing bespoke builds per client tends to hit a ceiling in the single digits before a solo operator is maxed out on hours. An agency with a genuinely repeatable configuration for one vertical can typically carry meaningfully more, because most of the delivery work is now templated rather than built fresh each time. Track your own time-per-client honestly before assuming you can add the next one.",
    },
    {
      q: "What should my first offer be?",
      a: "Narrower than feels comfortable. One vertical, one core outcome (usually: never miss a call, follow up on every lead within minutes, keep the calendar full), delivered as a flat monthly retainer rather than a one-off project. Resist bundling in every capability you're technically able to build — a focused offer is easier to explain, easier to price, and easier to prove results for than a broad one.",
    },
    {
      q: "Is this better than freelancing as an AI consultant?",
      a: "They're different businesses with different ceilings. Freelance AI consulting trades your hours for project fees and rarely compounds — each new client is roughly as much work as the last. An agency built around a retained, operated outcome in one vertical can compound: repeatable onboarding, recurring revenue, and referenceable results that generate the next client. It's also more work up front to set up correctly, and it fails in the specific ways described above if you skip the repeatability step.",
    },
  ],
  sources: [
    {
      label: "Model Context Protocol — \"What is the Model Context Protocol (MCP)?\"",
      url: "https://modelcontextprotocol.io/introduction",
    },
    {
      label: "GoHighLevel — pricing plans",
      url: "https://www.gohighlevel.com/pricing",
    },
  ],
};
