// Guide registry — the long-form article surface of the content engine.
// GENERATED by scratchpad/gen-guides-index.mjs from the guides/<slug>.ts files;
// the weekly content loop adds a file + re-runs the same codegen. Pure data +
// pure lookups so it's unit-testable and importable from server components,
// sitemap, llms.txt and the /guides/<slug>.md twin routes alike.

import { LAST_UPDATED } from "../alternative-pages";
import type { Guide, GuideCluster } from "./types";

import { guide as averageLeadResponseTimeByIndustry } from "./average-lead-response-time-by-industry";
import { guide as howToRespondToLeadsFaster } from "./how-to-respond-to-leads-faster";
import { guide as textOrCallANewLead } from "./text-or-call-a-new-lead";
import { guide as the5MinuteRuleForLeadResponse } from "./the-5-minute-rule-for-lead-response";
import { guide as whatIsSpeedToLead } from "./what-is-speed-to-lead";
import { guide as whyLeadsGoCold } from "./why-leads-go-cold";
import { guide as appointmentReminderTemplates } from "./appointment-reminder-templates";
import { guide as averageNoShowRateByIndustry } from "./average-no-show-rate-by-industry";
import { guide as howToReduceNoShows } from "./how-to-reduce-no-shows";
import { guide as howToSetUpAutomatedAppointmentReminders } from "./how-to-set-up-automated-appointment-reminders";
import { guide as shouldYouChargeANoShowFee } from "./should-you-charge-a-no-show-fee";
import { guide as smsVsEmailAppointmentReminders } from "./sms-vs-email-appointment-reminders";
import { guide as aiReceptionistVsAnsweringService } from "./ai-receptionist-vs-answering-service";
import { guide as howToAnswerBusinessCallsProfessionally } from "./how-to-answer-business-calls-professionally";
import { guide as howToHandleAfterHoursCalls } from "./how-to-handle-after-hours-calls";
import { guide as howToWriteAnAiReceptionistScript } from "./how-to-write-an-ai-receptionist-script";
import { guide as virtualReceptionistVsAiReceptionist } from "./virtual-receptionist-vs-ai-receptionist";
import { guide as whatShouldAReceptionistSayAnsweringThePhone } from "./what-should-a-receptionist-say-answering-the-phone";
import { guide as commonCustomerQuestionsToAnswerOnYourWebsite } from "./common-customer-questions-to-answer-on-your-website";
import { guide as faqPageExamplesForServiceBusinesses } from "./faq-page-examples-for-service-businesses";
import { guide as faqSchemaForLocalSeo } from "./faq-schema-for-local-seo";
import { guide as howManyFaqsShouldAWebsiteHave } from "./how-many-faqs-should-a-website-have";
import { guide as howToReduceRepetitiveCustomerQuestions } from "./how-to-reduce-repetitive-customer-questions";
import { guide as howToWriteAFaqPage } from "./how-to-write-a-faq-page";
import { guide as benefitsOfOnlineBookingForSmallBusiness } from "./benefits-of-online-booking-for-small-business";
import { guide as howToAddOnlineBookingToYourWebsite } from "./how-to-add-online-booking-to-your-website";
import { guide as howToLetCustomersBookOnline } from "./how-to-let-customers-book-online";
import { guide as howToReduceBookingAbandonment } from "./how-to-reduce-booking-abandonment";
import { guide as onlineBookingBestPractices } from "./online-booking-best-practices";
import { guide as onlineBookingVsPhoneBooking } from "./online-booking-vs-phone-booking";
import { guide as howToGetYourBusinessRecommendedByChatgpt } from "./how-to-get-your-business-recommended-by-chatgpt";
import { guide as howToShowUpInAiSearch } from "./how-to-show-up-in-ai-search";
import { guide as localSeoVsGeo } from "./local-seo-vs-geo";
import { guide as whatIsAnswerEngineOptimization } from "./what-is-answer-engine-optimization";
import { guide as whatIsGenerativeEngineOptimization } from "./what-is-generative-engine-optimization";
import { guide as isYourWebsiteLosingYouJobs } from "./is-your-website-losing-you-jobs";
import { guide as howToMakeAWebsiteForAServiceBusiness } from "./how-to-make-a-website-for-a-service-business";
import { guide as onlineBookingOptionsForServiceBusinesses } from "./online-booking-options-for-service-businesses";
import { guide as howToGetMoreGoogleReviews } from "./how-to-get-more-google-reviews";
import { guide as howToRespondToANegativeReview } from "./how-to-respond-to-a-negative-review";
import { guide as missedCallTextBack } from "./missed-call-text-back";
import { guide as onePersonCompanyOs } from "./one-person-company-os";
import { guide as howMuchDoesGohighlevelCost } from "./how-much-does-gohighlevel-cost";
import { guide as gohighlevelPricingPlansExplained } from "./gohighlevel-pricing-plans-explained";
import { guide as hiddenGohighlevelFees } from "./hidden-gohighlevel-fees";
import { guide as isGohighlevelAiEmployeeWorthIt } from "./is-gohighlevel-ai-employee-worth-it";
import { guide as bestGohighlevelAlternatives } from "./best-gohighlevel-alternatives";
import { guide as gohighlevelVsSeldonframe } from "./gohighlevel-vs-seldonframe";
import { guide as bestGohighlevelAlternativeForSolopreneurs } from "./best-gohighlevel-alternative-for-solopreneurs";
import { guide as gohighlevelVsHubspot } from "./gohighlevel-vs-hubspot";
import { guide as whyAgenciesLeaveGohighlevel } from "./why-agencies-leave-gohighlevel";
import { guide as isGohighlevelWorthItForSmallBusiness } from "./is-gohighlevel-worth-it-for-small-business";
import { guide as isGohighlevelHardToLearn } from "./is-gohighlevel-hard-to-learn";
import { guide as doINeedGohighlevel } from "./do-i-need-gohighlevel";
import { guide as howToSwitchFromGohighlevel } from "./how-to-switch-from-gohighlevel";
import { guide as howToReplaceGohighlevel } from "./how-to-replace-gohighlevel";
import { guide as howToPriceAnAiReceptionistService } from "./how-to-price-an-ai-receptionist-service";
import { guide as runClientAiOnYourOwnKeys } from "./run-client-ai-on-your-own-keys";
import { guide as gohighlevelSaasModeVsFlatPricing } from "./gohighlevel-saas-mode-vs-flat-pricing";
import { guide as whiteLabelAiFrontOfficeWithoutAgencyPro } from "./white-label-ai-front-office-without-agency-pro";
import { guide as howToMakeMoneySellingAiAgents } from "./how-to-make-money-selling-ai-agents";
import { guide as howMuchToChargeForAnAiAgent } from "./how-much-to-charge-for-an-ai-agent";
import { guide as aiAgentBusinessIdeas } from "./ai-agent-business-ideas";
import { guide as howToStartAnAiAutomationAgency } from "./how-to-start-an-ai-automation-agency";
import { guide as bestAiAgentMarketplaces } from "./best-ai-agent-marketplaces";
import { guide as whatIsAnMcpMarketplace } from "./what-is-an-mcp-marketplace";

export { LAST_UPDATED };
export type { Guide, GuideCluster, GuideSection, GuideFaq, GuideSource, GuideIntent } from "./types";

/** Human-readable label for each cluster, used on the /guides hub. */
export const CLUSTER_LABELS: Record<GuideCluster, string> = {
  "speed-to-lead": "Speed to lead & follow-up",
  "no-shows": "No-shows & reminders",
  "ai-receptionist": "AI receptionists & phone",
  "service-faq": "FAQs & customer questions",
  booking: "Online booking",
  "ai-visibility": "AI visibility & GEO",
  reviews: "Reviews & reputation",
  "ai-agents": "Running your business with AI agents",
  gohighlevel: "GoHighLevel alternatives & pricing",
  "sell-agents": "Building & selling AI agents",
};

export const GUIDES: Guide[] = [
  averageLeadResponseTimeByIndustry,
  howToRespondToLeadsFaster,
  textOrCallANewLead,
  the5MinuteRuleForLeadResponse,
  whatIsSpeedToLead,
  whyLeadsGoCold,
  appointmentReminderTemplates,
  averageNoShowRateByIndustry,
  howToReduceNoShows,
  howToSetUpAutomatedAppointmentReminders,
  shouldYouChargeANoShowFee,
  smsVsEmailAppointmentReminders,
  aiReceptionistVsAnsweringService,
  howToAnswerBusinessCallsProfessionally,
  howToHandleAfterHoursCalls,
  howToWriteAnAiReceptionistScript,
  virtualReceptionistVsAiReceptionist,
  whatShouldAReceptionistSayAnsweringThePhone,
  commonCustomerQuestionsToAnswerOnYourWebsite,
  faqPageExamplesForServiceBusinesses,
  faqSchemaForLocalSeo,
  howManyFaqsShouldAWebsiteHave,
  howToReduceRepetitiveCustomerQuestions,
  howToWriteAFaqPage,
  benefitsOfOnlineBookingForSmallBusiness,
  howToAddOnlineBookingToYourWebsite,
  howToLetCustomersBookOnline,
  howToReduceBookingAbandonment,
  onlineBookingBestPractices,
  onlineBookingVsPhoneBooking,
  howToGetYourBusinessRecommendedByChatgpt,
  howToShowUpInAiSearch,
  localSeoVsGeo,
  whatIsAnswerEngineOptimization,
  whatIsGenerativeEngineOptimization,
  isYourWebsiteLosingYouJobs,
  howToMakeAWebsiteForAServiceBusiness,
  onlineBookingOptionsForServiceBusinesses,
  howToGetMoreGoogleReviews,
  howToRespondToANegativeReview,
  missedCallTextBack,
  onePersonCompanyOs,
  howMuchDoesGohighlevelCost,
  gohighlevelPricingPlansExplained,
  hiddenGohighlevelFees,
  isGohighlevelAiEmployeeWorthIt,
  bestGohighlevelAlternatives,
  gohighlevelVsSeldonframe,
  bestGohighlevelAlternativeForSolopreneurs,
  gohighlevelVsHubspot,
  whyAgenciesLeaveGohighlevel,
  isGohighlevelWorthItForSmallBusiness,
  isGohighlevelHardToLearn,
  doINeedGohighlevel,
  howToSwitchFromGohighlevel,
  howToReplaceGohighlevel,
  howToPriceAnAiReceptionistService,
  runClientAiOnYourOwnKeys,
  gohighlevelSaasModeVsFlatPricing,
  whiteLabelAiFrontOfficeWithoutAgencyPro,
  howToMakeMoneySellingAiAgents,
  howMuchToChargeForAnAiAgent,
  aiAgentBusinessIdeas,
  howToStartAnAiAutomationAgency,
  bestAiAgentMarketplaces,
  whatIsAnMcpMarketplace,
];

export function getGuide(slug: string): Guide {
  const found = GUIDES.find((g) => g.slug === slug);
  if (!found) throw new Error(`unknown guide slug: ${slug}`);
  return found;
}

export function allGuideSlugs(): string[] {
  return GUIDES.map((g) => g.slug);
}

export function guidesInCluster(cluster: GuideCluster): Guide[] {
  return GUIDES.filter((g) => g.cluster === cluster);
}

/** Clusters that actually have at least one published guide, label + members. */
export function populatedClusters(): { cluster: GuideCluster; label: string; guides: Guide[] }[] {
  const seen = new Set<GuideCluster>();
  const order: GuideCluster[] = [];
  for (const g of GUIDES) {
    if (!seen.has(g.cluster)) {
      seen.add(g.cluster);
      order.push(g.cluster);
    }
  }
  return order.map((cluster) => ({ cluster, label: CLUSTER_LABELS[cluster], guides: guidesInCluster(cluster) }));
}
