// Guide registry — the long-form article surface of the content engine.
// GENERATED by scratchpad/gen-guides-index.mjs from the guides/<slug>.ts files;
// the weekly content loop adds a file + re-runs the same codegen. Pure data +
// pure lookups so it's unit-testable and importable from server components,
// sitemap, llms.txt and the /guides/<slug>.md twin routes alike.

import { LAST_UPDATED } from "../alternative-pages";
import type { Guide, GuideCluster } from "./types";

import { guide as averageLeadResponseTimeByIndustry } from "./average-lead-response-time-by-industry";
import { guide as howToRespondToLeadsFaster } from "./how-to-respond-to-leads-faster";
import { guide as textOrCallANewLead } from "./text-or-call-a-new-lead";
import { guide as the5MinuteRuleForLeadResponse } from "./the-5-minute-rule-for-lead-response";
import { guide as whatIsSpeedToLead } from "./what-is-speed-to-lead";
import { guide as whyLeadsGoCold } from "./why-leads-go-cold";
import { guide as appointmentReminderTemplates } from "./appointment-reminder-templates";
import { guide as averageNoShowRateByIndustry } from "./average-no-show-rate-by-industry";
import { guide as howToReduceNoShows } from "./how-to-reduce-no-shows";
import { guide as howToSetUpAutomatedAppointmentReminders } from "./how-to-set-up-automated-appointment-reminders";
import { guide as shouldYouChargeANoShowFee } from "./should-you-charge-a-no-show-fee";
import { guide as smsVsEmailAppointmentReminders } from "./sms-vs-email-appointment-reminders";
import { guide as aiReceptionistVsAnsweringService } from "./ai-receptionist-vs-answering-service";
import { guide as howToAnswerBusinessCallsProfessionally } from "./how-to-answer-business-calls-professionally";
import { guide as howToHandleAfterHoursCalls } from "./how-to-handle-after-hours-calls";
import { guide as howToWriteAnAiReceptionistScript } from "./how-to-write-an-ai-receptionist-script";
import { guide as virtualReceptionistVsAiReceptionist } from "./virtual-receptionist-vs-ai-receptionist";
import { guide as whatShouldAReceptionistSayAnsweringThePhone } from "./what-should-a-receptionist-say-answering-the-phone";
import { guide as commonCustomerQuestionsToAnswerOnYourWebsite } from "./common-customer-questions-to-answer-on-your-website";
import { guide as faqPageExamplesForServiceBusinesses } from "./faq-page-examples-for-service-businesses";
import { guide as faqSchemaForLocalSeo } from "./faq-schema-for-local-seo";
import { guide as howManyFaqsShouldAWebsiteHave } from "./how-many-faqs-should-a-website-have";
import { guide as howToReduceRepetitiveCustomerQuestions } from "./how-to-reduce-repetitive-customer-questions";
import { guide as howToWriteAFaqPage } from "./how-to-write-a-faq-page";
import { guide as benefitsOfOnlineBookingForSmallBusiness } from "./benefits-of-online-booking-for-small-business";
import { guide as howToAddOnlineBookingToYourWebsite } from "./how-to-add-online-booking-to-your-website";
import { guide as howToLetCustomersBookOnline } from "./how-to-let-customers-book-online";
import { guide as howToReduceBookingAbandonment } from "./how-to-reduce-booking-abandonment";
import { guide as onlineBookingBestPractices } from "./online-booking-best-practices";
import { guide as onlineBookingVsPhoneBooking } from "./online-booking-vs-phone-booking";
import { guide as howToGetYourBusinessRecommendedByChatgpt } from "./how-to-get-your-business-recommended-by-chatgpt";
import { guide as howToShowUpInAiSearch } from "./how-to-show-up-in-ai-search";
import { guide as localSeoVsGeo } from "./local-seo-vs-geo";
import { guide as whatIsAnswerEngineOptimization } from "./what-is-answer-engine-optimization";
import { guide as whatIsGenerativeEngineOptimization } from "./what-is-generative-engine-optimization";

export { LAST_UPDATED };
export type { Guide, GuideCluster, GuideSection, GuideFaq, GuideSource, GuideIntent } from "./types";

/** Human-readable label for each cluster, used on the /guides hub. */
export const CLUSTER_LABELS: Record<GuideCluster, string> = {
  "speed-to-lead": "Speed to lead & follow-up",
  "no-shows": "No-shows & reminders",
  "ai-receptionist": "AI receptionists & phone",
  "service-faq": "FAQs & customer questions",
  booking: "Online booking",
  "ai-visibility": "AI visibility & GEO",
};

export const GUIDES: Guide[] = [
  averageLeadResponseTimeByIndustry,
  howToRespondToLeadsFaster,
  textOrCallANewLead,
  the5MinuteRuleForLeadResponse,
  whatIsSpeedToLead,
  whyLeadsGoCold,
  appointmentReminderTemplates,
  averageNoShowRateByIndustry,
  howToReduceNoShows,
  howToSetUpAutomatedAppointmentReminders,
  shouldYouChargeANoShowFee,
  smsVsEmailAppointmentReminders,
  aiReceptionistVsAnsweringService,
  howToAnswerBusinessCallsProfessionally,
  howToHandleAfterHoursCalls,
  howToWriteAnAiReceptionistScript,
  virtualReceptionistVsAiReceptionist,
  whatShouldAReceptionistSayAnsweringThePhone,
  commonCustomerQuestionsToAnswerOnYourWebsite,
  faqPageExamplesForServiceBusinesses,
  faqSchemaForLocalSeo,
  howManyFaqsShouldAWebsiteHave,
  howToReduceRepetitiveCustomerQuestions,
  howToWriteAFaqPage,
  benefitsOfOnlineBookingForSmallBusiness,
  howToAddOnlineBookingToYourWebsite,
  howToLetCustomersBookOnline,
  howToReduceBookingAbandonment,
  onlineBookingBestPractices,
  onlineBookingVsPhoneBooking,
  howToGetYourBusinessRecommendedByChatgpt,
  howToShowUpInAiSearch,
  localSeoVsGeo,
  whatIsAnswerEngineOptimization,
  whatIsGenerativeEngineOptimization,
];

export function getGuide(slug: string): Guide {
  const found = GUIDES.find((g) => g.slug === slug);
  if (!found) throw new Error(`unknown guide slug: ${slug}`);
  return found;
}

export function allGuideSlugs(): string[] {
  return GUIDES.map((g) => g.slug);
}

export function guidesInCluster(cluster: GuideCluster): Guide[] {
  return GUIDES.filter((g) => g.cluster === cluster);
}

/** Clusters that actually have at least one published guide, label + members. */
export function populatedClusters(): { cluster: GuideCluster; label: string; guides: Guide[] }[] {
  const seen = new Set<GuideCluster>();
  const order: GuideCluster[] = [];
  for (const g of GUIDES) {
    if (!seen.has(g.cluster)) {
      seen.add(g.cluster);
      order.push(g.cluster);
    }
  }
  return order.map((cluster) => ({ cluster, label: CLUSTER_LABELS[cluster], guides: guidesInCluster(cluster) }));
}
