import type { Guide } from "./types";

export const guide: Guide = {
  slug: "where-to-sell-ai-agents",
  title: "Where to Sell AI Agents: 7 Channels Ranked by Effort and Revenue Reality",
  description:
    "Direct sale, white-label through agencies, your own site, freelance platforms, marketplaces, resellers, consumer stores — 7 channels for selling AI agents, ranked honestly by effort and how fast money actually shows up.",
  targetKeyword: "where to sell ai agents",
  intent: "commercial",
  cluster: "sell-agents",
  relatedTool: "/tools/agency-margin-calculator",
  relatedBest: "/marketplace",
  dek: "\"Where do I sell an AI agent\" sounds like a discovery problem, but it's really an ownership problem: every channel is a trade between how much distribution it hands you and how much of the customer relationship (and margin) it takes in return. Here are the 7 real channels, ranked by realistic revenue for a solo builder or small agency — not by hype.",
  sections: [
    {
      h2: "The real question isn't \"where\" — it's who owns the customer",
      body: "Every channel for selling an AI agent sits somewhere on the same trade-off: the more distribution a channel hands you, the more it usually takes — a cut of revenue, ownership of the customer relationship, or both. A cold outreach retainer gives you 100% of the customer and 0% built-in distribution; a consumer app store gives you access to millions of users and almost no say in who finds you, what they pay, or whether you ever hear from them again. Neither end of that spectrum is wrong. The mistake is picking a channel without noticing which end of the trade you're making.\n\nRanked by realistic revenue for a solo builder or small agency, roughly best-to-worst: (1) direct sale to local or SMB businesses on retainer, (2) white-label through other agencies — you build, they sell under their own brand, (3) your own vertical productized-service site, (4) freelance platforms like Upwork or Fiverr, (5) agent marketplaces, (6) reseller or affiliate programs for platforms you didn't build, (7) consumer app stores like the GPT Store. That order isn't a law of nature — a builder with an existing audience might do better starting at (7), and a builder inside an agency network might skip straight to (2) — but for someone starting from zero, it's the order that tends to produce a first dollar fastest and keeps the most of what you earn.",
    },
    {
      h2: "The money channels: direct sale and white-label through agencies",
      body: "Direct sale to local and service businesses — plumbers, dentists, salons, HVAC — is ranked first because it's the only channel where you control every variable: the pitch, the price, the timeline, and the relationship after the sale. A week of effort looks like prospecting (finding businesses with a provable, nameable pain — a missed call, no online booking), building a demo on the prospect's actual business before the meeting, and pitching the one-booked-job math. First revenue realistically arrives whenever you close your first retainer, which depends entirely on how many prospects you can reach and how sharp the demo is — there's no honest universal number to give here, and the field-manual version of this channel, with scripts and objection handling, lives in the companion guide on selling to local businesses. What you give up: nothing to a platform, but everything to your own hustle — there's no channel here doing the selling for you.\n\nWhite-label through other agencies — building agents that other agencies resell under their own brand to their own clients — is ranked second because it inherits the same ownership (you set your price to the agency, you own the build) while trading direct-sales effort for relationship-building effort: instead of pitching one business at a time, you pitch one agency once and get access to their whole client roster. A week of effort looks like finding agencies already selling something adjacent (web design, marketing, IT support) who don't want to build AI agents themselves, and proving your build quality on one client before asking for the roster. First revenue arrives on roughly the same timeline as direct sales but compounds faster once one agency relationship is proven, because each new client the agency signs is incremental revenue for you without incremental prospecting. What you give up: your name on the finished product (it ships as theirs), and some pricing control if the agency negotiates hard on the wholesale rate.",
    },
    {
      h2: "The grind channels: your own site and freelance platforms",
      body: "A vertical productized-service site — a landing page selling a specific, packaged agent (\"AI receptionist for dental offices,\" priced and scoped) to a niche you pick — is ranked third because it's direct-sale ownership without direct-sale prospecting effort; the trade is that you now need inbound instead, which is its own grind. A week of effort looks like SEO content, a clear pricing page, and enough proof (case studies, a live demo) to convert someone who arrived with zero relationship to you. First revenue realistically takes longer to arrive than direct outreach, because you're waiting on search or referral traffic to find you rather than finding the buyer yourself — hedge any specific timeline claim you see for this channel; it depends entirely on the niche's search volume and your content cadence. What you give up: the fast, controllable timeline of direct sales, in exchange for a channel that can eventually run with less of your active selling time once it's built.\n\nFreelance platforms — Upwork, Fiverr, and similar — are ranked fourth, and honestly lower than their traffic numbers suggest, because of a trade most builders underweight until they hit it: the platform, not you, owns the buyer relationship for the first project, and every job runs through the platform's fee structure taken off the top. Neither platform publishes a page we could independently verify for this piece, so state it plainly and qualitatively rather than quoting a number: expect a real service fee on every job, standard for the category. A week of effort looks like building a profile, bidding on postings, and delivering fast enough to earn reviews that unlock better-paying work. First revenue can arrive faster than the other channels here — some buyers hire within days of a good proposal — but the per-project fee and platform-mediated relationship mean it's a weaker foundation for a recurring retainer than a client you found and closed yourself. What you give up: a cut of every job, and the buyer's contact information until (if) the relationship moves off-platform.",
    },
    {
      h2: "The leverage and lottery channels: marketplaces, resellers, consumer stores",
      body: "Agent marketplaces are ranked fifth — worth doing, but as a credibility and discovery layer stacked on top of a direct-sales motion, not a replacement for one. The category itself splits into consumer app stores, enterprise exchanges, and deploy-and-operate marketplaces, each with different gatekeeping and payout mechanics; the full breakdown of which is which, and how each one actually pays, is its own piece — see the marketplace comparison page rather than re-deriving it here. A week of effort looks like polishing a listing and, for deploy-and-operate marketplaces specifically, making the agent easy to try before a buyer commits. First revenue is genuinely unpredictable — some listings get discovered quickly, most don't — because you're relying on the platform's search and browse behavior rather than your own outreach. What you give up: a share of revenue on marketplace-sourced sales, and some control over how your agent is presented next to competitors.\n\nReseller or affiliate programs for platforms you didn't build — earning a commission for referring customers to someone else's AI product — are ranked sixth because you're selling someone else's roadmap and someone else's pricing power with no path to owning the build or the customer long-term. A week of effort is genuinely low (share a link, make the case in conversations you're already having), which is exactly why the payout per hour tends to be low too. First revenue can arrive quickly for an easy referral, but there's no compounding: each sale is a one-off commission, not a growing book of your own clients. What you give up: essentially everything except the commission — no product ownership, no client relationship, no pricing say.\n\nConsumer app stores — the GPT Store and similar — are ranked last for a builder trying to make a living, not because they're bad, but because they're a distribution lottery. The GPT Store went free to publish to in May 2024 after launching to paying users only in January 2024, per Wikipedia's summary of the platform, and OpenAI has tested usage-based payouts for builders, but the public record doesn't clearly confirm a fully live, specific revenue-share rate today — treat any number you see quoted for this as unverified until OpenAI's own current documentation states it. A week of effort is low (publish and hope for discovery), and that's the whole problem: so is everyone else's, and the store's own discovery mechanics — not your sales skill — decide who gets found. First revenue, if it arrives at all, is unpredictable and platform-dependent. What you give up: essentially all pricing and relationship control, in exchange for a shot at reach you can't get any other way.",
    },
    {
      h2: "Stacking channels sanely",
      body: "The temptation, especially early, is to try to be everywhere at once — a marketplace listing, a GPT Store publish, an Upwork profile, and cold outreach, all in the same week. In practice that produces zero traction anywhere, because each channel has its own skill (a good demo pitch is a different skill from writing SEO copy is a different skill from optimizing a marketplace listing) and splitting a week seven ways means none of them get enough attempts to actually work.\n\nThe sane order: start with direct sales, even if it's not where you plan to end up, because the discipline of pitching a real business forces your offer to get sharp — you'll find out fast whether \"AI agent\" means anything to a buyer or whether you need to talk about missed calls and booked jobs instead. Once direct sales is producing a repeatable pitch and a couple of paying clients, add exactly one leverage channel second — white-label through one agency relationship, or one marketplace listing — rather than adding all of them simultaneously. Prove the second channel works before adding a third.\n\nWhere SeldonFrame fits into this, disclosed plainly since we build the product: the appeal of a channel-agnostic build is that you're not rebuilding the agent seven times for seven channels. One build on SeldonFrame works across most of the channels above at once — sell it direct to a client on retainer, white-label the same build for an agency's client roster, list it on the SF marketplace, or rent it out via a signed MCP key rather than handing over the source. The platform is $29/mo flat with the first workspace free and BYOK for model costs, and SF only takes a cut — a GMV fee stepping down from 5% to 3% to 2% — when SF is actually the channel that brought the buyer; sell direct and that fee doesn't apply. That's a real advantage for stacking channels without rebuilding for each one, and it's also, plainly, the sales pitch in this paragraph.",
    },
  ],
  faq: [
    {
      q: "What's the fastest channel to a first dollar?",
      a: "Direct sale to a local or SMB business, honestly. It's the only channel where you control the entire timeline — you find the prospect, build the demo, pitch, and close, with no platform's discovery algorithm or review queue in the way. It's also the most work per dollar in a given week, which is the trade: fastest doesn't mean easiest, it means most within your control.",
    },
    {
      q: "Can I sell the same agent on multiple channels at once?",
      a: "Yes, and it's one of the better reasons to build the agent on a platform rather than bespoke code per client — the same build can go direct to a client, white-label through an agency, and sit on a marketplace listing simultaneously. The caveat is bandwidth, not technology: each channel needs its own attention (a pitch, a relationship, a listing), so stacking channels works once one is already producing, not as a day-one strategy.",
    },
    {
      q: "Are freelance platforms like Upwork or Fiverr worth it?",
      a: "It depends on what you're optimizing for. They can produce a first project faster than cold outreach because demand is already there and browsing. But the platform takes a service fee off every job and mediates the buyer relationship, at least initially, which makes it a weaker foundation for a recurring retainer than a client you found and closed yourself. Treat it as a way to get reps and reviews early, not as the channel you build a business on long-term.",
    },
    {
      q: "When is listing on an agent marketplace actually worth the effort?",
      a: "Once you already have a build worth listing and some credibility to point to — a marketplace listing works best as a discovery and trust layer stacked on top of direct sales, not as a first channel on its own. If you're starting from zero with no clients and no proof, a marketplace listing alone is unlikely to be where your first revenue comes from; add it after direct sales is producing, not instead of it.",
    },
    {
      q: "Should I try to get into a consumer app store like the GPT Store?",
      a: "Only if reach itself is the goal, not near-term revenue — publishing is low-effort, but so is everyone else's, and the store's own discovery mechanics decide who gets found, not your sales skill. Builders trying to make a living from AI agents are generally better served ranking this channel last: it's a lottery ticket worth holding if it's free to enter, not a plan to build a business around.",
    },
  ],
  sources: [
    {
      label: "Wikipedia — GPT Store",
      url: "https://en.wikipedia.org/wiki/GPT_Store",
    },
    {
      label: "AWS Marketplace — AI Agents and Tools",
      url: "https://aws.amazon.com/marketplace/solutions/ai-agents-and-tools/",
    },
    {
      label: "HighLevel — official pricing page (conventional agency-stack cost reference)",
      url: "https://www.gohighlevel.com/pricing",
    },
  ],
};
