// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "headline": z.string().min(2),
  "items": z.array(z.object({
      "question": z.string().min(3),
      "answer": z.string().min(15)
    })).min(4).max(8)
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "faq",
  version: "1.0.0",
  surface: "landing-section" as const,
  sectionType: "faq" as const,
  description: `Frequently-asked-questions section addressing the actual concerns that block visitors from booking — pricing, scheduling, what to expect, scope, refunds.`,
} as const;
