// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "headline": z.string().min(4),
  "subhead": z.string().optional(),
  "cta_primary": z.object({
    "label": z.string().min(2).max(40),
    "href": z.enum(["/book", "/intake"] as const)
  }),
  "cta_secondary": z.object({
    "label": z.string().min(2).max(40),
    "href": z.string()
  }).optional()
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "cta",
  version: "1.0.0",
  surface: "landing-section" as const,
  sectionType: "mid-cta" as const,
  description: `Mid-page call-to-action — a focused conversion moment between sections. Singular outcome, low friction, urgency without pressure.`,
} as const;
