// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "headline": z.string().min(2),
  "subhead": z.string().optional(),
  "layout": z.enum(["grid-3", "grid-4", "tabs", "stats"] as const).optional(),
  "items": z.array(z.object({
      "icon": z.string().min(2),
      "title": z.string().min(2),
      "description": z.string().min(8),
      "price_from": z.string().optional(),
      "category": z.string().optional()
    })).min(3).max(8)
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "services",
  version: "1.0.0",
  surface: "landing-section" as const,
  sectionType: "services-grid" as const,
  description: `Services / offerings grid with one card per service, each with a distinct icon and a short customer-language description.`,
} as const;
