"use client";

import Link from "next/link";
import { useActionState, useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  CheckCircle,
  Circle,
  CircleDashedIcon,
  ExternalLink,
  FileText,
  Layers,
  MessageCircleDashedIcon,
  Paintbrush,
  PaperclipIcon,
  RefreshCw,
  SparklesIcon,
  ThumbsDown,
  ThumbsUp,
  WandSparklesIcon,
} from "lucide-react";
import {
  runSeldonItAction,
  saveSeldonBlockAction,
  type SeldonRunResult,
  type SeldonRunState,
  type SeldonSavedBlock,
  type SeldonSessionItem,
} from "@/lib/ai/seldon-actions";
import { recordSeldonFeedbackAction } from "@/lib/ai/record-seldon-feedback";
import { SELDON_CALM_PROGRESS_MESSAGES, SELDON_PROGRESS_INTERVAL_MS } from "@/lib/ai/progress-messages";
import { SeldonResultActions } from "@/components/seldon-result-actions";

type ChatMessage = {
  id: string;
  role: "user" | "assistant";
  content: string;
};

type SessionPlan = {
  title: string;
  totalSteps: number;
  steps: Array<{
    stepNumber: number;
    description: string;
    blockType: "form" | "email" | "booking" | "page" | "automation";
  }>;
};

type SeldonUsageInfo = {
  includedUsed: number;
  includedLimit: number;
  meteredUsed: number;
  byokUsed: number;
  totalThisMonth: number;
  mode: "byok" | "included" | "metered";
};

const initialState: SeldonRunState = { ok: false };
const processingSteps = [...SELDON_CALM_PROGRESS_MESSAGES];

function normalizeSummaryLine(summary: string) {
  return summary.split("\n")[0]?.replace(/^[-\s]*/, "") || "Generated by Seldon";
}

function PlanCard({
  plan,
  completedCount,
}: {
  plan: SessionPlan;
  completedCount: number;
}) {
  return (
    <div className="rounded-lg border border-zinc-700 bg-zinc-900/30 p-4 mb-4">
      <div className="flex items-center gap-2 mb-2">
        <Layers className="h-4 w-4 text-teal-400" />
        <span className="text-sm font-medium text-zinc-200">{plan.title}</span>
        <span className="text-xs text-zinc-500">{plan.totalSteps} steps</span>
      </div>
      <div className="space-y-1">
        {plan.steps.map((step) => {
          const isDone = step.stepNumber <= completedCount;
          return (
            <div key={`${plan.title}-${step.stepNumber}`} className="flex items-center gap-2 text-xs">
              {isDone ? <CheckCircle className="h-3.5 w-3.5 text-emerald-500" /> : <Circle className="h-3.5 w-3.5 text-zinc-600" />}
              <span className={isDone ? "text-zinc-400" : "text-zinc-500"}>{step.description}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function UpdateResultCard({ result, onPrompt }: { result: SeldonRunResult; onPrompt: (value: string) => void }) {
  const changeText = result.changes || result.description || normalizeSummaryLine(result.summary);

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-5 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <RefreshCw className="h-4 w-4 text-blue-400" />
          <span className="font-semibold text-base text-zinc-100">Updated: {result.blockName}</span>
        </div>
        <span className="text-xs px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-400">Modified</span>
      </div>

      <p className="text-sm text-zinc-400">{changeText}</p>

      <SeldonResultActions actions={result.actions} onPrompt={onPrompt} />
    </div>
  );
}

function getSessionPlan(item: SeldonSessionItem): SessionPlan | null {
  for (let index = item.messages.length - 1; index >= 0; index -= 1) {
    const plan = item.messages[index] as { plan?: SessionPlan };
    if (plan?.plan) {
      return plan.plan;
    }
  }

  return null;
}

function getSessionCreatedEntityCount(item: SeldonSessionItem) {
  const ids = new Set<string>();

  for (const message of item.messages) {
    if (!Array.isArray(message.createdEntities)) {
      continue;
    }

    for (const entity of message.createdEntities) {
      ids.add(entity.id);
    }
  }

  return ids.size;
}

function CreateOrPlanResultCard({ result, onPrompt }: { result: SeldonRunResult; onPrompt: (value: string) => void }) {
  const description = result.description || normalizeSummaryLine(result.summary);
  const status = result.status ?? "live";
  const [copied, setCopied] = useState(false);

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-5 space-y-3">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 min-w-0">
          <CheckCircle className="h-5 w-5 text-emerald-500" />
          <span className="font-semibold text-base text-zinc-100 truncate">{result.blockName}</span>
        </div>
        {status === "live" ? <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400">Live</span> : null}
        {status === "needs-integration" ? <span className="text-xs px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-400">Needs Setup</span> : null}
        {status === "error" ? <span className="text-xs px-2 py-0.5 rounded-full bg-red-500/10 text-red-400">Error</span> : null}
        {status === "draft" ? <span className="text-xs px-2 py-0.5 rounded-full bg-zinc-500/20 text-zinc-300">Draft</span> : null}
      </div>

      <p className="text-sm text-zinc-400">{description}</p>

      {result.integrationNote ? (
        <p className="text-xs text-amber-400/80 flex items-center gap-1.5">
          <AlertCircle className="h-3.5 w-3.5 flex-shrink-0" />
          {result.integrationNote}
        </p>
      ) : null}

      <div className="space-y-2 pt-1">
        <div className="flex items-center gap-3">
          {result.publicUrl ? (
            <a href={result.publicUrl} target="_blank" rel="noopener noreferrer" className="text-sm text-teal-400 hover:text-teal-300 flex items-center gap-1">
              Open <ExternalLink className="h-3.5 w-3.5" />
            </a>
          ) : null}
          {result.publicUrl ? (
            <button
              type="button"
              onClick={async () => {
                const absoluteUrl = result.publicUrl?.startsWith("http")
                  ? result.publicUrl
                  : `${window.location.origin}${result.publicUrl?.startsWith("/") ? result.publicUrl : `/${result.publicUrl}`}`;
                await navigator.clipboard.writeText(absoluteUrl || "");
                setCopied(true);
                window.setTimeout(() => setCopied(false), 1400);
              }}
              className="text-sm text-zinc-500 hover:text-zinc-300"
            >
              {copied ? "Copied!" : "Copy Link"}
            </button>
          ) : null}
          {result.editUrl ? (
            <a href={result.editUrl} className="text-sm text-indigo-400 hover:text-indigo-300 flex items-center gap-1">
              Edit Visually <Paintbrush className="h-3.5 w-3.5" />
            </a>
          ) : null}
        </div>
        <SeldonResultActions actions={result.actions} onPrompt={onPrompt} />
      </div>
    </div>
  );
}

function BlueprintResultCard({
  result,
  onViewBlockMd,
}: {
  result: SeldonRunResult;
  onViewBlockMd: (value: SeldonRunResult) => void;
}) {
  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-5 space-y-3">
      <div className="flex items-center gap-2">
        <FileText className="h-5 w-5 text-blue-400" />
        <span className="font-semibold text-base text-zinc-100">Blueprint: {result.blockName}</span>
      </div>
      <p className="text-sm text-zinc-400">This block type doesn&apos;t exist yet. Here&apos;s a blueprint Seldon designed.</p>
      <div className="flex gap-3 pt-1">
        <button
          type="button"
          onClick={() => onViewBlockMd(result)}
          className="text-sm px-3 py-1.5 bg-zinc-800 rounded hover:bg-zinc-700 text-zinc-300"
        >
          View Blueprint
        </button>
        <form action={saveSeldonBlockAction}>
          <input type="hidden" name="blockId" value={result.blockId} />
          <input type="hidden" name="blockName" value={result.blockName} />
          <input type="hidden" name="blockMd" value={result.blockMd} />
          <button type="submit" className="text-sm px-3 py-1.5 bg-teal-600 rounded hover:bg-teal-500 text-white">
            Save to My Blocks
          </button>
        </form>
      </div>
    </div>
  );
}

function toBlueprintResult(blueprint: Record<string, unknown>): SeldonRunResult {
  const name = String(blueprint.name ?? blueprint.title ?? "Untitled Blueprint").trim() || "Untitled Blueprint";
  const markdown = typeof blueprint.blockMd === "string"
    ? blueprint.blockMd
    : `# BLOCK.md\n\n${JSON.stringify(blueprint, null, 2)}`;

  return {
    blockId: `blueprint-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    blockName: name,
    blockMd: markdown,
    description: "Blueprint generated",
    summary: "- Blueprint generated",
    status: "draft",
    fromInventory: false,
    installMode: "review",
    openPath: "/seldon",
    savePath: "/seldon",
  };
}

function SuggestionChips({ suggestions, onPick }: { suggestions: string[]; onPick: (prompt: string) => void }) {
  if (suggestions.length === 0) {
    return null;
  }

  return (
    <div className="flex flex-wrap gap-2">
      {suggestions.map((suggestion) => (
        <button
          key={suggestion}
          type="button"
          className="rounded-full border border-border px-3 py-1.5 text-xs hover:bg-accent"
          onClick={() => onPick(suggestion)}
        >
          {suggestion}
        </button>
      ))}
    </div>
  );
}

function ResultCard({
  result,
  action,
  onViewBlockMd,
  onPrompt,
}: {
  result: SeldonRunResult;
  action?: SeldonRunState["action"];
  onViewBlockMd: (value: SeldonRunResult) => void;
  onPrompt: (value: string) => void;
}) {
  if (action === "blueprint") {
    return <BlueprintResultCard result={result} onViewBlockMd={onViewBlockMd} />;
  }

  if (action === "update") {
    return <UpdateResultCard result={result} onPrompt={onPrompt} />;
  }

  return <CreateOrPlanResultCard result={result} onPrompt={onPrompt} />;
}

export function SeldonPageClient({
  allowed,
  planId,
  usage,
  sessions,
  savedBlocks,
  initialPrompt = "",
}: {
  allowed: boolean;
  planId: string | null;
  usage: SeldonUsageInfo;
  sessions: SeldonSessionItem[];
  savedBlocks: SeldonSavedBlock[];
  initialPrompt?: string;
}) {
  const [state, action, pending] = useActionState(runSeldonItAction, initialState);
  const [selectedResult, setSelectedResult] = useState<SeldonRunResult | null>(null);
  const [description, setDescription] = useState(initialPrompt);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [processingIndex, setProcessingIndex] = useState(0);
  const [feedbackByMessage, setFeedbackByMessage] = useState<Record<string, -1 | 1>>({});

  async function submitFeedback(feedbackScore: -1 | 1, messageId: string) {
    if (feedbackByMessage[messageId]) {
      return;
    }

    const payload = new FormData();
    payload.set("feedbackScore", String(feedbackScore));
    payload.set("sessionId", activeSessionId ?? state.sessionId ?? "");
    payload.set("messageId", messageId);

    const result = await recordSeldonFeedbackAction(payload);
    if (result.ok) {
      setFeedbackByMessage((current) => ({
        ...current,
        [messageId]: feedbackScore,
      }));
    }
  }

  useEffect(() => {
    if (!pending) {
      return;
    }

    const timer = window.setInterval(() => {
      setProcessingIndex((current) => (current + 1) % processingSteps.length);
    }, SELDON_PROGRESS_INTERVAL_MS);

    return () => window.clearInterval(timer);
  }, [pending]);

  const activeSession = useMemo(
    () => sessions.find((entry) => entry.id === activeSessionId) ?? null,
    [activeSessionId, sessions],
  );

  const activeSessionResults = useMemo(
    () => (activeSession?.messages ?? []).flatMap((message) => message.results ?? []),
    [activeSession],
  );

  const statePlan = state.plan as SessionPlan | null | undefined;
  const activeSessionPlan = useMemo(() => (activeSession ? getSessionPlan(activeSession) : null), [activeSession]);
  const activeSessionCreatedCount = useMemo(() => (activeSession ? getSessionCreatedEntityCount(activeSession) : 0), [activeSession]);
  const isFreeTier = !planId || planId === "free" || planId === "starter";
  const includedLimitLabel = Number.isFinite(usage.includedLimit) ? usage.includedLimit : 50;

  const customizeExamples = [
    {
      icon: "📅",
      prompt: "Add a pre-call questionnaire to discovery calls",
    },
    {
      icon: "✉️",
      prompt: "Make my welcome email include my podcast link",
    },
    {
      icon: "📋",
      prompt: "Add branching logic to my intake form",
    },
    {
      icon: "🌐",
      prompt: "Add testimonials to my landing page",
    },
  ];

  const buildExamples = [
    { icon: "🎯", prompt: "Build a quiz funnel that qualifies leads" },
    { icon: "👤", prompt: "Create a client portal with session history" },
    { icon: "🎁", prompt: "Set up a referral program with tracking" },
    { icon: "💳", prompt: "Build a 3-installment payment plan via Stripe" },
    { icon: "📊", prompt: "Create a weekly pipeline report sent every Monday" },
  ];

  function fillPrompt(prompt: string) {
    setDescription(prompt);
    setTimeout(() => {
      const textarea = document.getElementById("seldon-description") as HTMLTextAreaElement | null;
      textarea?.focus();
    }, 50);
  }

  const hasHistoryState =
    pending ||
    Boolean(state.error) ||
    Boolean(state.message) ||
    Boolean(state.results?.length) ||
    chatMessages.length > 0 ||
    Boolean(activeSession);

  const sanitizedError = state.error?.includes("Failed to parse Seldon response") ? undefined : state.error;
  const assistantContent = sanitizedError
    ? sanitizedError
    : [
        state.message,
        ...(state.results ?? []).map((result) => `${result.blockName}: ${result.summary || "BLOCK.md generated successfully"}`),
      ]
        .filter(Boolean)
        .join("\n\n");

  return (
    <div className="flex h-screen overflow-hidden bg-background">
      <div className="hidden md:block w-64 border-r border-border">
        <div className="flex h-full w-full flex-col bg-sidebar border-r border-sidebar-border">
          <div className="flex items-center justify-between p-3 border-b border-sidebar-border">
            <button type="button" className="w-full justify-start gap-2 px-2 h-10 inline-flex items-center rounded-md text-sm font-medium hover:bg-accent">
              <SparklesIcon className="size-4" />
              <span className="text-sm">New Session</span>
            </button>
          </div>

          <div className="flex-1 overflow-y-auto no-scrollbar">
            <div className="p-3 space-y-4">
              <div className="space-y-1">
                <div className="px-2 py-1.5">
                  <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Recent</p>
                </div>
                {sessions.length === 0 ? <p className="px-2 text-sm text-muted-foreground">No Seldon history yet.</p> : null}
                {sessions.map((item) => (
                  <div key={item.id} className="group/item relative flex items-center rounded-md overflow-hidden">
                    <button
                      type="button"
                      onClick={() => {
                        setActiveSessionId(item.id);
                        setChatMessages(
                          item.messages.map((message, index) => ({
                            id: `${item.id}-${index}`,
                            role: message.role,
                            content: message.content,
                          })),
                        );
                      }}
                      className="flex-1 justify-start gap-2 px-2 text-left h-auto py-1.5 min-w-0 pr-8 inline-flex items-center rounded-md text-sm font-medium hover:bg-accent"
                    >
                      <MessageCircleDashedIcon className="size-4 shrink-0" />
                      <span className="text-sm truncate min-w-0">{item.title}</span>
                    </button>
                  </div>
                ))}
                {sessions.map((item) => {
                  const plan = getSessionPlan(item);
                  if (!plan) {
                    return null;
                  }

                  const createdCount = getSessionCreatedEntityCount(item);
                  return (
                    <div key={`${item.id}-plan-progress`} className="px-2 text-xs text-zinc-500 mt-0.5">
                      {createdCount}/{plan.totalSteps} steps complete
                    </div>
                  );
                })}
              </div>

              <div className="space-y-1">
                <div className="px-2 py-1.5">
                  <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">My Blocks</p>
                </div>
                {savedBlocks.length === 0 ? <p className="px-2 text-sm text-muted-foreground">No saved blocks yet.</p> : null}
                {savedBlocks.map((item) => (
                  <div key={item.id} className="group/item relative flex items-center rounded-md overflow-hidden">
                    <button
                      type="button"
                      onClick={() => {
                        setSelectedResult({
                          blockId: item.id,
                          blockName: item.name,
                          blockMd: item.blockMd,
                          summary: "Saved block package",
                          fromInventory: false,
                          installMode: "instant",
                          openPath: "/seldon",
                          savePath: "/seldon",
                        });
                      }}
                      className="flex-1 justify-start gap-2 px-2 text-left h-auto py-1.5 min-w-0 pr-8 inline-flex items-center rounded-md text-sm font-medium hover:bg-accent"
                    >
                      <SparklesIcon className="size-4 shrink-0" />
                      <span className="text-sm truncate min-w-0">{item.name}</span>
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-1 flex-col overflow-hidden">
        <div className="flex-1 overflow-hidden relative">
          <div className="relative z-10 h-full flex flex-col">
            <div className="flex-1 overflow-y-auto px-4 md:px-8 py-8">
              <div className="max-w-[640px] mx-auto space-y-6">
                {!hasHistoryState ? (
                  <div className="flex h-full flex-col items-center justify-center px-4 md:px-8">
                    <div className="w-full max-w-[640px] space-y-9 -mt-12">
                      <div className="flex justify-center">
                        <div className="flex items-center justify-center size-8 rounded-full">
                          <SparklesIcon className="size-20" />
                        </div>
                      </div>

                      <div className="space-y-4 text-center">
                        <h1 className="text-2xl font-semibold tracking-tight">Hey! I&apos;m Seldon</h1>
                        <p className="text-base text-muted-foreground">Describe what you want to build or customize.</p>
                      </div>

                      <div className="space-y-5 mt-6 text-left">
                        <div className="space-y-2">
                          <p className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">Customize a block</p>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                            {customizeExamples.map((example) => (
                              <button
                                key={example.prompt}
                                type="button"
                                className="text-left rounded-xl border border-border p-3 hover:bg-accent/40 transition-colors"
                                onClick={() => fillPrompt(example.prompt)}
                              >
                                <p className="text-sm text-foreground">
                                  <span className="mr-1.5" aria-hidden="true">{example.icon}</span>
                                  &quot;{example.prompt}&quot;
                                </p>
                              </button>
                            ))}
                          </div>
                        </div>

                        <div className="space-y-2">
                          <p className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">Build something new</p>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                            {buildExamples.map((example) => (
                              <button
                                key={example.prompt}
                                type="button"
                                className="text-left rounded-xl border border-border p-3 hover:bg-accent/40 transition-colors"
                                onClick={() => fillPrompt(example.prompt)}
                              >
                                <p className="text-sm text-foreground">
                                  <span className="mr-1.5" aria-hidden="true">{example.icon}</span>
                                  &quot;{example.prompt}&quot;
                                </p>
                              </button>
                            ))}
                          </div>
                        </div>

                        <p className="text-xs text-center text-muted-foreground">Click any to start — or type your own.</p>
                      </div>
                    </div>
                  </div>
                ) : null}

                {!allowed ? (
                  <div className="rounded-2xl border border-border bg-secondary dark:bg-card p-1">
                    <div className="rounded-xl border border-border dark:border-transparent bg-card dark:bg-secondary p-4 space-y-4">
                      <p className="text-sm leading-relaxed">Upgrade to Cloud Pro to Seldon custom blocks.</p>
                      <Link href="/settings/billing" className="gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-4 py-2 bg-primary text-primary-foreground hover:bg-primary/90">
                        Upgrade Plan
                      </Link>
                    </div>
                  </div>
                ) : null}

                {chatMessages.length > 0 ? (
                  <div className="space-y-3">
                    {chatMessages.map((message) => (
                      <div key={message.id} className="rounded-2xl border border-border bg-secondary dark:bg-card p-1">
                        <div className="rounded-xl border border-border dark:border-transparent bg-card dark:bg-secondary p-4 space-y-2">
                          <p className="text-xs uppercase tracking-wide text-muted-foreground">{message.role === "user" ? "You" : "Seldon"}</p>
                          <p className="text-sm whitespace-pre-wrap leading-relaxed">{message.content}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : null}

                {pending ? (
                  <div className="rounded-2xl border border-border bg-secondary dark:bg-card p-1">
                    <div className="rounded-xl border border-border dark:border-transparent bg-card dark:bg-secondary px-6 py-4">
                      <p className="text-sm text-muted-foreground flex items-center gap-2 animate-pulse">
                        <span className="size-2 rounded-full bg-primary" />
                        {processingSteps[processingIndex]}
                      </p>
                    </div>
                  </div>
                ) : null}

                {!pending && assistantContent ? (
                  <div className="rounded-2xl border border-border bg-secondary dark:bg-card p-1">
                    <div className="rounded-xl border border-border dark:border-transparent bg-card dark:bg-secondary p-4 space-y-2">
                      <p className="text-xs uppercase tracking-wide text-muted-foreground">Seldon</p>
                      <p className="text-sm whitespace-pre-wrap leading-relaxed">{assistantContent}</p>
                      {state.message ? (
                        <div className="flex items-center gap-1.5 pt-1 text-muted-foreground">
                          <button
                            type="button"
                            className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-accent"
                            aria-label="Thumbs up"
                            onClick={() => void submitFeedback(1, `builder-${activeSessionId ?? state.sessionId ?? "latest"}`)}
                            disabled={Boolean(feedbackByMessage[`builder-${activeSessionId ?? state.sessionId ?? "latest"}`])}
                          >
                            <ThumbsUp className="h-3.5 w-3.5" />
                          </button>
                          <button
                            type="button"
                            className="inline-flex h-7 w-7 items-center justify-center rounded-md hover:bg-accent"
                            aria-label="Thumbs down"
                            onClick={() => void submitFeedback(-1, `builder-${activeSessionId ?? state.sessionId ?? "latest"}`)}
                            disabled={Boolean(feedbackByMessage[`builder-${activeSessionId ?? state.sessionId ?? "latest"}`])}
                          >
                            <ThumbsDown className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      ) : null}
                    </div>
                  </div>
                ) : null}

                {state.results?.length ? (
                  <div className="space-y-3">
                    {state.action === "plan" && statePlan ? (
                      <PlanCard plan={statePlan} completedCount={Math.max(1, Math.min(statePlan.totalSteps, state.results.length))} />
                    ) : null}
                    {state.results.map((result) => (
                      <ResultCard key={result.blockId} result={result} action={state.action} onViewBlockMd={setSelectedResult} onPrompt={fillPrompt} />
                    ))}
                    <SuggestionChips suggestions={state.suggestions ?? []} onPick={fillPrompt} />
                  </div>
                ) : null}

                {!state.results?.length && state.action === "blueprint" && state.blueprint ? (
                  <BlueprintResultCard result={toBlueprintResult(state.blueprint)} onViewBlockMd={setSelectedResult} />
                ) : null}

                {activeSessionResults.length > 0 ? (
                  <div className="space-y-3">
                    {activeSessionPlan ? <PlanCard plan={activeSessionPlan} completedCount={activeSessionCreatedCount} /> : null}
                    {activeSessionResults.map((result) => (
                      <ResultCard key={`session-${result.blockId}`} result={result} onViewBlockMd={setSelectedResult} onPrompt={fillPrompt} />
                    ))}
                  </div>
                ) : null}

                {selectedResult ? (
                  <div className="fixed inset-y-0 right-0 z-50 w-full max-w-[560px] border-l border-border bg-card px-6 py-5 shadow-xl">
                    <div className="flex h-full flex-col gap-4">
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium">{selectedResult.blockName} BLOCK.md</p>
                        <div className="flex items-center gap-2">
                          <button type="button" className="gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-4 py-2 border border-input bg-background hover:bg-accent" onClick={async () => {
                            await navigator.clipboard.writeText(selectedResult.blockMd);
                          }}>
                            Copy
                          </button>
                          <button type="button" className="gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-4 py-2 border border-input bg-background hover:bg-accent" onClick={() => {
                            const blob = new Blob([selectedResult.blockMd], { type: "text/markdown;charset=utf-8" });
                            const url = URL.createObjectURL(blob);
                            const link = document.createElement("a");
                            link.href = url;
                            link.download = `${selectedResult.blockName.toLowerCase().replace(/[^a-z0-9-]+/g, "-")}.md`;
                            link.click();
                            URL.revokeObjectURL(url);
                          }}>
                            Download .md
                          </button>
                          <button type="button" className="gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-4 py-2 border border-input bg-background hover:bg-accent" onClick={() => setSelectedResult(null)}>
                            Close
                          </button>
                        </div>
                      </div>
                      <pre className="min-h-0 flex-1 overflow-auto rounded-xl border border-border bg-secondary p-4 text-xs leading-relaxed whitespace-pre-wrap">
                        {selectedResult.blockMd}
                      </pre>
                    </div>
                  </div>
                ) : null}
              </div>
            </div>

            <div className="border-t border-border px-4 md:px-8 py-[17px]">
              <div className="max-w-[640px] mx-auto">
                <form
                  action={action}
                  className="rounded-2xl border border-border bg-secondary dark:bg-card p-1"
                  onSubmit={() => {
                    const trimmed = description.trim();
                    if (!trimmed) {
                      return;
                    }

                    setChatMessages((current) => [
                      ...current,
                      {
                        id: `user-${Date.now()}`,
                        role: "user",
                        content: trimmed,
                      },
                    ]);
                  }}
                >
                  <div className="rounded-xl border border-border dark:border-transparent bg-card dark:bg-secondary">
                    <input type="hidden" name="sessionId" value={activeSessionId ?? state.sessionId ?? ""} />
                    <textarea
                      id="seldon-description"
                      name="description"
                      placeholder="Describe what you want to build..."
                      value={description}
                      onChange={(event) => setDescription(event.target.value)}
                      required
                      className="min-h-[120px] resize-none border-0 bg-transparent px-4 py-3 text-base placeholder:text-muted-foreground/60 focus-visible:ring-0 focus-visible:ring-offset-0 w-full"
                      onKeyDown={(event) => {
                        if (event.key === "Enter" && !event.shiftKey) {
                          event.preventDefault();
                          if (description.trim()) {
                            event.currentTarget.form?.requestSubmit();
                          }
                        }
                      }}
                    />

                    <div className="flex items-center justify-between px-4 py-3 border-t border-border/50">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          className="size-7 rounded-full border border-border dark:border-input bg-card dark:bg-secondary hover:bg-accent inline-flex items-center justify-center"
                        >
                          <PaperclipIcon className="size-4 text-muted-foreground" />
                        </button>
                        <button
                          type="button"
                          className="gap-1.5 h-7 rounded-full border border-border dark:border-input bg-card dark:bg-secondary hover:bg-accent px-3 inline-flex items-center"
                        >
                          <CircleDashedIcon className="size-4 text-muted-foreground" />
                          <span className="hidden sm:inline text-sm text-muted-foreground/70">Deep Search</span>
                        </button>
                        <button
                          type="button"
                          className="gap-1.5 h-7 rounded-full border border-border dark:border-input bg-card dark:bg-secondary hover:bg-accent px-3 inline-flex items-center"
                        >
                          <SparklesIcon className="size-4 text-muted-foreground" />
                          <span className="hidden sm:inline text-sm text-muted-foreground/70">Think</span>
                        </button>
                      </div>

                      <button type="submit" disabled={pending || !allowed || description.trim().length === 0} className="h-7 px-4 gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
                        {pending ? "Seldoning..." : "Send"}
                      </button>
                    </div>
                  </div>
                </form>

                <div className="flex flex-wrap items-center justify-center gap-2 mt-3">
                  {[...customizeExamples, ...buildExamples].slice(0, 3).map((example) => (
                    <button
                      key={example.prompt}
                      type="button"
                      className="gap-2 inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-4 py-2 border border-input bg-background hover:bg-accent"
                      onClick={() => fillPrompt(example.prompt)}
                    >
                      <WandSparklesIcon className="size-4" />
                      <span className="max-w-[220px] truncate">{example.prompt}</span>
                    </button>
                  ))}
                </div>

                {isFreeTier ? (
                  <p className="mt-3 text-center text-xs text-muted-foreground">
                    {usage.includedUsed}/{includedLimitLabel} this month
                    {usage.includedUsed >= Math.floor(includedLimitLabel * 0.8) ? (
                      <span className="text-amber-500"> · Running low</span>
                    ) : null}
                  </p>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
