// v1.3.0 — LLM-generated personality cache.
//
// Pattern (Karpathy): the model is the personality generator, the
// validator is the quality gate, the cache is the scaling layer. New
// niches (pet grooming, photography, accounting, …) get a custom
// PersonalitySchema generated on the first request, validator-gated,
// then cached by `business_type_key` so subsequent workspaces of the
// same niche hit the cache (zero LLM cost, fully deterministic).
//
// Hardcoded personalities (general, hvac, dental, legal, agency,
// coaching, medspa) are SEED CACHE rows — instant lookup + few-shot
// examples for the generator. They serve as the "what good looks
// like" demonstration; the generator can also write back to this
// table once it produces validated output.

import { sql } from "drizzle-orm";
import {
  boolean,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import type { CRMPersonality } from "@/lib/crm/personality";

export type PersonalityCacheSource = "seed" | "llm" | "manual";

export const personalityCache = pgTable(
  "personality_cache",
  {
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),
    /** Stable lookup key derived from operator input (services +
     *  description). Lowercased, hyphenated, max 64 chars. Examples:
     *  "roofing", "pet-grooming", "wedding-photography",
     *  "tax-accounting". Two operators in the same vertical resolve
     *  to the same key → second operator gets the cached schema. */
    businessTypeKey: text("business_type_key").notNull(),
    /** The full validated PersonalitySchema. Strictly conforms to
     *  CRMPersonality + passes checkPersonalityCompleteness(). */
    schema: jsonb("schema").$type<CRMPersonality>().notNull(),
    /** Provenance: 'seed' (hardcoded in code), 'llm' (generated by
     *  Claude), 'manual' (operator-edited). Drives observability +
     *  selective regeneration. */
    source: text("source").$type<PersonalityCacheSource>().notNull().default("llm"),
    /** Did this row pass checkPersonalityCompleteness at INSERT
     *  time? Always true for seed; expected true for llm but kept
     *  as a flag in case validation rules tighten later. */
    validated: boolean("validated").notNull().default(true),
    /** How many workspaces have used this cached schema. Updated
     *  via UPDATE … usage_count = usage_count + 1 on every cache
     *  hit. Drives cost analytics + identifies popular niches. */
    usageCount: integer("usage_count").notNull().default(0),
    /** Model identifier when source='llm'. Helps regenerate stale
     *  rows when a newer model ships. */
    generatedBy: text("generated_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    // One row per business_type_key; INSERT … ON CONFLICT lets us
    // "first writer wins" without a race on parallel workspace
    // creation hitting the same niche for the first time.
    businessTypeKeyUidx: uniqueIndex("personality_cache_business_type_key_uidx").on(
      table.businessTypeKey,
    ),
  }),
);

export type PersonalityCacheRow = typeof personalityCache.$inferSelect;
