// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "eyebrow": z.string().optional(),
  "headline": z.string().min(4),
  "subhead": z.string().min(8),
  "cta_primary": z.object({
    "label": z.string().min(2).max(40),
    "href": z.enum(["/book", "/intake"] as const)
  }),
  "cta_secondary": z.object({
    "label": z.string().min(2).max(40),
    "href": z.string()
  }).optional(),
  "background_image_query": z.string().min(2),
  "background_video_query": z.string().min(2).optional(),
  "shiny_word": z.string().min(2).max(30).optional(),
  "variant": z.enum(["split-image-right", "full-bleed", "founder-portrait"] as const).optional(),
  // v1.44.0 — template id from hero-templates/registry.ts. When set, the
  // public renderer dispatches to HERO_TEMPLATES[template] (cinematic-aura,
  // viktor-light, velorah-editorial, nexora-light, securify-bold,
  // stellar-tabs-white). Absent → renderer falls back to the legacy
  // variant system. Hand-edited extension; matches the SKILL.md schema
  // and will roundtrip through the next `pnpm blocks:emit` cleanly.
  "template": z.enum([
    "cinematic-aura",
    "viktor-light",
    "velorah-editorial",
    "nexora-light",
    "securify-bold",
    "stellar-tabs-white",
  ] as const).optional()
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "hero",
  version: "1.0.0",
  surface: "landing-section" as const,
  sectionType: "hero" as const,
  description: `Above-the-fold hero with quantified value claim, primary CTA, and supporting visual.`,
} as const;
