// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "title": z.string().min(2),
  "description": z.string().min(12),
  "duration_minutes": z.number().min(15).max(240),
  "location_kind": z.enum(["on-site-business", "on-site-customer", "phone", "video", "hybrid"] as const),
  "weekly_availability": z.object({
    "mon": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "tue": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "wed": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "thu": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "fri": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "sat": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable(),
    "sun": z.tuple([z.number().min(0).max(24), z.number().min(0).max(24)]).nullable()
  }),
  "form_fields": z.array(z.object({
      "id": z.string().min(1),
      "label": z.string().min(2),
      "type": z.enum(["text", "email", "phone", "textarea", "select"] as const),
      "required": z.boolean().optional(),
      "placeholder": z.string().optional(),
      "options": z.array(z.string()).optional()
    })).optional()
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "booking",
  version: "1.0.0",
  surface: "booking" as const,
  sectionType: "booking" as const,
  description: `The booking page (calendar) — what visitors see when they hit /book. Title, description, slot duration, location kind, weekly availability hours, and the form fields collected at booking time.`,
} as const;
