// ============================================================================
// AUTO-GENERATED by `pnpm blocks:emit` from ../SKILL.md frontmatter.
// DO NOT EDIT BY HAND — re-run `pnpm blocks:emit` after editing SKILL.md.
// ============================================================================
//
// The codegen contract (v1.5.0): every consumer of a block's prop schema
// reads from this file (via lib/page-blocks/registry.ts). The SKILL.md
// frontmatter is the SINGLE source of truth; any drift between this file
// and SKILL.md is caught by the `pnpm blocks:emit --check` CI step.

import { z } from "zod";

export const PropsSchema = z.object({
  "headline": z.string().min(2),
  "body": z.string().min(30),
  "owner_name": z.string().optional(),
  "owner_title": z.string().optional(),
  "photo_query": z.string().optional()
});

export type Props = z.infer<typeof PropsSchema>;

export const meta = {
  name: "about",
  version: "1.0.0",
  surface: "landing-section" as const,
  sectionType: "about" as const,
  description: `About-the-business section — who they are, why they started, what makes them specific. Trust-building, not corporate.`,
} as const;
