// v1.4.0 — POST /api/v1/workspace/v2/blocks
//
// Persists a block instance generated by the IDE agent. The agent reads
// the block's SKILL.md, generates props with its own LLM, and posts here.
// We validate, render, replace the matching section in the workspace's
// landing page, persist both the block_instances row + the updated
// landing_pages row, and return the block id + public URL.
//
// Auth: workspace bearer token (Authorization: Bearer wst_…) — same
// shape as every other authenticated v1 route. The bearer's org is
// the only workspace this call can touch.

import { NextResponse } from "next/server";
import { guardApiRequest } from "@/lib/api/guard";
import { logEvent } from "@/lib/observability/log";
import { persistBlockForWorkspace } from "@/lib/page-blocks/persist";

type Body = {
  workspace_id?: unknown;
  block_name?: unknown;
  generation_prompt?: unknown;
  props?: unknown;
  customization?: unknown;
};

export async function POST(request: Request) {
  const guard = await guardApiRequest(request);
  if ("error" in guard) return guard.error;

  const body = (await request.json().catch(() => ({}))) as Body;
  const workspaceId = typeof body.workspace_id === "string" ? body.workspace_id.trim() : "";
  const blockName = typeof body.block_name === "string" ? body.block_name.trim() : "";
  const generationPrompt =
    typeof body.generation_prompt === "string" ? body.generation_prompt : "";
  const props = body.props;
  const customizationObj =
    body.customization && typeof body.customization === "object"
      ? (body.customization as { prompt?: unknown; source?: unknown })
      : null;

  if (!workspaceId || !blockName || !generationPrompt || props == null) {
    return NextResponse.json(
      {
        ok: false,
        error: "missing_required_field",
        required: ["workspace_id", "block_name", "generation_prompt", "props"],
      },
      { status: 400 },
    );
  }

  // The bearer token's org MUST match the workspace_id in the body —
  // prevents cross-workspace tampering even with a leaked-and-stolen
  // body shape from another session.
  if (guard.orgId !== workspaceId) {
    return NextResponse.json(
      {
        ok: false,
        error: "workspace_mismatch",
        message: "Bearer token does not match workspace_id.",
      },
      { status: 403 },
    );
  }

  const customization =
    customizationObj && typeof customizationObj.prompt === "string"
      ? {
          prompt: customizationObj.prompt,
          source:
            typeof customizationObj.source === "string"
              ? customizationObj.source
              : undefined,
        }
      : undefined;

  const result = await persistBlockForWorkspace({
    workspaceId,
    blockName,
    generationPrompt,
    props,
    customization,
  });

  if (!result.ok) {
    logEvent(
      "v2_persist_block_failed",
      {
        block_name: blockName,
        error: result.error,
        validation_errors: result.validation_errors,
      },
      { request, orgId: workspaceId, status: 422, severity: "warn" },
    );
    return NextResponse.json(result, { status: 422 });
  }

  logEvent(
    "v2_persist_block_succeeded",
    {
      block_name: result.block_name,
      template_version: result.template_version,
      had_customization: Boolean(customization),
    },
    { request, orgId: workspaceId, status: 200 },
  );

  return NextResponse.json(result, { status: 200 });
}
