// Marketplace seed catalog — real-but-tasteful fallback agents shown ONLY when
// no kind:'agent' listings are published yet, so the storefront always renders
// with credible content. Ported from the Claude Design output
// (sf-mkt-design/SeldonFrame Marketplace.dc.html, the AGENTS array).
//
// IMPORTANT (noted in the task report): these are starter/demo listings. The
// browse + listing pages prefer live DB listings via listMarketplaceAgentsFromDb
// and fall back to this catalog only when the published set is empty. Seed slugs
// are stable so the listing route resolves them.
//
// TRANSPARENCY (2026-06-22): seeds carry NO fabricated social proof. installs,
// rating, reviewCount are 0 and the reviews arrays are empty, so a brand-new
// marketplace reads as genuinely NEW ("just launched"), not fake-popular. The UI
// renders a "New" badge for any agent with isSeed/zero installs (see
// installsLabel + the isSeed guards in the card + listing detail). The blurbs,
// sample conversations, highlights, and tools are illustrative product copy —
// kept so the storefront still demonstrates what each agent does.

import type { StorefrontAgent } from "./marketplace-data";

export const MARKETPLACE_SEED: StorefrontAgent[] = [
  {
    slug: "receptionist",
    name: "AI Receptionist",
    category: "Receptionist",
    icon: "phone",
    surfaces: ["voice", "sms"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 2900,
    featured: true,
    builder: "Northlight Ops",
    verified: true,
    tagline: "Answers every call and books the job — even at 2am.",
    blurb:
      "Picks up on the first ring, answers questions about your services, hours, and pricing, captures the lead, and books straight into your calendar. It texts a confirmation, logs the customer, and only hands off to you when something genuinely needs a human.",
    highlights: [
      "Never sends a caller to voicemail",
      "Books directly into your calendar",
      "Texts confirmations automatically",
      "Escalates the rare call that needs you",
    ],
    tools: [
      { label: "Calendar", icon: "calendar" },
      { label: "Business phone line", icon: "phone" },
      { label: "Customer records", icon: "users" },
      { label: "Service catalog", icon: "file" },
    ],
    sampleChannel: "phone call",
    channelIcon: "phone",
    sampleTitle: "Inbound call · transcribed live",
    sample: [
      { role: "customer", text: "Hi, do you do emergency AC repair? My unit just died." },
      { role: "agent", text: "We do — sorry you're dealing with that in this heat. I can get a tech out today. What's the address?" },
      { role: "customer", text: "It's 4408 Mesa Verde, Tempe." },
      { role: "agent", text: "Got it. We have a 2:00 PM or a 4:30 PM open today. Which works better?" },
      { role: "customer", text: "2 works, please." },
      { role: "agent", text: "Booked for 2:00 PM. I've texted you a confirmation and your tech Daniel's details. Anything else?" },
    ],
    outcome: "Answered in 1 ring · 38s · booked a $420 service call",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "review-requester",
    name: "Review Requester",
    category: "Reviews",
    icon: "starLine",
    surfaces: ["sms", "email"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 1900,
    featured: true,
    builder: "Northlight Ops",
    verified: true,
    tagline: "Turns finished jobs into 5-star reviews, automatically.",
    blurb:
      "A couple of hours after a job is marked complete, it texts the customer a warm, personal ask with a one-tap review link. It follows up once if there is no response, routes unhappy customers to you privately first, and never spams.",
    highlights: [
      "Sends at the perfect post-job moment",
      "One-tap link to Google or Facebook",
      "Catches unhappy customers privately",
      "Stops after one gentle follow-up",
    ],
    tools: [
      { label: "Customer records", icon: "users" },
      { label: "SMS + email", icon: "mail" },
      { label: "Google Business", icon: "star" },
      { label: "Job history", icon: "calendar" },
    ],
    sampleChannel: "text message",
    channelIcon: "smartphone",
    sampleTitle: "Outbound SMS · 2h after job",
    sample: [
      { role: "agent", text: "Hi Karen — thanks for choosing Northlight today. Glad we got the kitchen drain sorted. Mind leaving a quick review? It really helps a small shop like ours." },
      { role: "customer", text: "Happy to! You guys were fast." },
      { role: "agent", text: "Means a lot, thank you. Here's the link — takes about 20 seconds: g.page/r/northlight" },
      { role: "customer", text: "Done — left 5 stars." },
    ],
    outcome: "Review captured · rating up from 4.4 to 4.8 in 60 days",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "win-back",
    name: "Win-Back",
    category: "Reactivation",
    icon: "repeat",
    surfaces: ["sms", "email"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 1900,
    featured: false,
    builder: "Loop & Co",
    verified: true,
    tagline: "Re-engages cold customers before they forget you.",
    blurb:
      "Watches your customer list for people who have gone quiet, then reaches out with a relevant, well-timed nudge — a seasonal tune-up, a maintenance reminder, a “we miss you” with a real reason to come back. It books the return visit on the spot.",
    highlights: [
      "Finds customers who have gone quiet",
      "Sends a reason, not just a discount",
      "Books the return visit in-thread",
      "Respects do-not-contact instantly",
    ],
    tools: [
      { label: "Customer records", icon: "users" },
      { label: "SMS + email", icon: "mail" },
      { label: "Calendar", icon: "calendar" },
      { label: "Service history", icon: "repeat" },
    ],
    sampleChannel: "text message",
    channelIcon: "smartphone",
    sampleTitle: "Outbound SMS · re-engagement",
    sample: [
      { role: "agent", text: "Hi Tom, it's been about 6 months since your last tune-up with Northlight. Want me to grab you a spot before the cold hits?" },
      { role: "customer", text: "Oh, good reminder. Yeah, let's do it." },
      { role: "agent", text: "Easy — I've got Thursday 9:00 AM or Friday 1:00 PM." },
      { role: "customer", text: "Thursday works." },
      { role: "agent", text: "Done. Confirmation texted. Talk soon, Tom." },
    ],
    outcome: "Reactivated · $310 booked from a dormant customer",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "quote-assistant",
    name: "Quote Assistant",
    category: "Quote",
    icon: "file",
    surfaces: ["chat", "email"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 3900,
    featured: false,
    builder: "Northlight Ops",
    verified: true,
    tagline: "Builds and sends quotes while you stay on the job.",
    blurb:
      "Gathers the details a customer needs priced, gives an instant ballpark from your rate card, and drafts a clean, itemized quote for your approval. Once you tap send, it follows up so quotes stop going cold in your inbox.",
    highlights: [
      "Instant ballpark from your rate card",
      "Itemized quote drafted for approval",
      "Follows up so quotes don't go cold",
      "Converts an accepted quote to a booking",
    ],
    tools: [
      { label: "Rate card", icon: "dollar" },
      { label: "Email + chat", icon: "message" },
      { label: "Customer records", icon: "users" },
      { label: "Calendar", icon: "calendar" },
    ],
    sampleChannel: "website chat",
    channelIcon: "message",
    sampleTitle: "Website chat · new visitor",
    sample: [
      { role: "customer", text: "Can I get a ballpark for replacing a 3-ton AC unit?" },
      { role: "agent", text: "Sure — for a 3-ton system most installs run $5,400–$7,200 depending on the unit and your ductwork. Want me to put together a detailed quote?" },
      { role: "customer", text: "Yes please." },
      { role: "agent", text: "Sent to your email and texted a copy. It's good for 30 days — reply 'book' and I'll schedule the install." },
    ],
    outcome: "Quote sent in 90s · accepted next morning",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "booking-concierge",
    name: "Booking Concierge",
    category: "Support",
    icon: "calendar",
    surfaces: ["voice", "chat", "sms"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 0,
    featured: true,
    builder: "Tidewater Labs",
    verified: true,
    tagline: "Fills your calendar and handles every reschedule.",
    blurb:
      "Owns your booking flow end to end across voice, chat, and text — finding slots, confirming, sending reminders, and handling the reschedules and cancellations that used to interrupt your day. It keeps your calendar tidy so you never double-book.",
    highlights: [
      "Books across voice, chat, and SMS",
      "Sends reminders that cut no-shows",
      "Handles reschedules without you",
      "Never double-books your calendar",
    ],
    tools: [
      { label: "Calendar", icon: "calendar" },
      { label: "Phone + SMS", icon: "phone" },
      { label: "Reminders", icon: "clock" },
      { label: "Customer records", icon: "users" },
    ],
    sampleChannel: "text message",
    channelIcon: "smartphone",
    sampleTitle: "Inbound SMS · reschedule",
    sample: [
      { role: "customer", text: "Need to reschedule my Tuesday appointment." },
      { role: "agent", text: "No problem — I see your 10:00 AM drain inspection Tuesday. Want me to move it?" },
      { role: "customer", text: "Yeah, later in the week if possible." },
      { role: "agent", text: "I have Thursday 11:00 AM or Friday 8:30 AM open." },
      { role: "customer", text: "Thursday 11." },
      { role: "agent", text: "Moved to Thursday 11:00 AM. Confirmation on its way." },
    ],
    outcome: "Rescheduled in 30s · no-show avoided · free to install",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "speed-to-lead",
    name: "Speed-to-Lead",
    category: "Support",
    icon: "zap",
    surfaces: ["sms"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 1900,
    featured: false,
    builder: "Tidewater Labs",
    verified: true,
    tagline: "Texts every new lead within 60 seconds.",
    blurb:
      "The moment a lead comes in from a form, ad, or call, it texts them back in under a minute — while you are still their first thought. It qualifies, answers the obvious questions, and books or routes a hot lead straight to you.",
    highlights: [
      "Replies in under 60 seconds",
      "Qualifies before it reaches you",
      "Books the hot leads on the spot",
      "Works your forms, ads, and missed calls",
    ],
    tools: [
      { label: "Lead forms", icon: "download" },
      { label: "SMS", icon: "smartphone" },
      { label: "Calendar", icon: "calendar" },
      { label: "Customer records", icon: "users" },
    ],
    sampleChannel: "text message",
    channelIcon: "smartphone",
    sampleTitle: "Outbound SMS · 47s after a form fill",
    sample: [
      { role: "agent", text: "Hi Alex — thanks for reaching out to Northlight about a water heater install. I can help right now. Are you looking to replace or repair?" },
      { role: "customer", text: "Replace, it's leaking." },
      { role: "agent", text: "Got it. I can have someone out today or tomorrow morning — which works?" },
      { role: "customer", text: "Today if you can." },
      { role: "agent", text: "Done, booked for 3:00 PM today. You'll get a confirmation text shortly." },
    ],
    outcome: "Replied in 47s · lead booked before a competitor called back",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "social-autopilot",
    name: "Social Autopilot",
    category: "Social",
    icon: "share",
    surfaces: ["chat", "email"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 2900,
    featured: false,
    builder: "Bright Signal",
    verified: false,
    tagline: "Replies to comments and DMs so leads never wait.",
    blurb:
      "Watches your business profiles for comments and messages, replies in your voice within minutes, and pulls genuine inquiries into a booking conversation. It flags anything sensitive for you rather than guessing.",
    highlights: [
      "Replies to comments and DMs fast",
      "Turns inquiries into bookings",
      "Posts on a schedule you approve",
      "Flags anything sensitive for you",
    ],
    tools: [
      { label: "Social profiles", icon: "share" },
      { label: "Messaging", icon: "message" },
      { label: "Calendar", icon: "calendar" },
      { label: "Customer records", icon: "users" },
    ],
    sampleChannel: "comment reply",
    channelIcon: "message",
    sampleTitle: "Public comment · replied in 3 min",
    sample: [
      { role: "customer", text: "Do you guys do commercial jobs too, or just residential?" },
      { role: "agent", text: "We do both — we handle commercial HVAC across the whole valley. Want me to have someone send a quick quote?" },
      { role: "customer", text: "Sure, that'd be great." },
      { role: "agent", text: "Perfect — I'll DM you to grab a couple details and get that moving today." },
    ],
    outcome: "Public reply in 3 min · moved to a private quote",
    reviews: [],
    isSeed: true,
  },
  {
    slug: "front-desk-support",
    name: "Front Desk Support",
    category: "Support",
    icon: "headphones",
    surfaces: ["chat", "email", "sms"],
    installs: 0,
    rating: "0",
    reviewCount: 0,
    priceCents: 0,
    featured: false,
    builder: "Bright Signal",
    verified: false,
    tagline: "Answers the everyday questions so you don't have to.",
    blurb:
      "Handles the steady stream of “what are your hours,” “do you service my area,” and “how much is X” across chat, email, and text — instantly and accurately from your own info. It escalates the genuinely tricky ones to you with full context.",
    highlights: [
      "Answers FAQs from your own info",
      "Works chat, email, and text",
      "Escalates the tricky ones with context",
      "Free to install and run",
    ],
    tools: [
      { label: "Knowledge base", icon: "file" },
      { label: "Chat + email", icon: "message" },
      { label: "SMS", icon: "smartphone" },
      { label: "Business hours", icon: "clock" },
    ],
    sampleChannel: "website chat",
    channelIcon: "message",
    sampleTitle: "Website chat · returning visitor",
    sample: [
      { role: "customer", text: "What are your hours and do you take Saturday appointments?" },
      { role: "agent", text: "We're open 7 AM–6 PM weekdays and 8 AM–2 PM Saturdays. Want me to book you a Saturday slot?" },
      { role: "customer", text: "Yes, this Saturday morning." },
      { role: "agent", text: "Booked for 9:00 AM Saturday. Confirmation texted!" },
    ],
    outcome: "Answered + booked in under a minute · free to install",
    reviews: [],
    isSeed: true,
  },
];

/** Look up a single seed agent by slug. */
export function findSeedAgent(slug: string): StorefrontAgent | undefined {
  return MARKETPLACE_SEED.find((a) => a.slug === slug);
}
