import Anthropic from "@anthropic-ai/sdk";
import { ZodError } from "zod";
import { routingResultSchema, soulV4Schema, type RoutingResult, type SoulV4 } from "@/lib/soul-compiler/schema";

const DEFAULT_MODEL = process.env.SOUL_COMPILER_MODEL?.trim() || "claude-sonnet-4-20250514";
const ROUTING_MAX_TOKENS = 1200;
const EXTRACTION_MAX_TOKENS = 6000;

export const soulCompilerSystemPrompt = `You are SoulCompiler v4 for SeldonFrame — an open-source business operating system that creates complete, personalized business infrastructure from one text message.

Core rules:
- Input can be a scraped URL or plain-text description.
- Audience is strictly dual: "service" (coaching/agency/consulting/freelance) OR "product" (fast-shipping SaaS/MVP/micro-SaaS).
- Detect audience, choose closest base_framework, customize every edge case.
- Hybrids are NOT allowed in one workspace. Set split_recommendation = true and explain briefly.
- pipeline_stages should contain 4-7 stages. More than 7 indicates over-complication.
- booking_config and pricing_config inner schemas (use exactly these structures):
  - booking_config (only when audience_type = "service"):
    {
      "enabled": boolean,
      "default_duration_minutes": number,
      "buffer_minutes": number,
      "services": array of objects with "name", "price", "description"
    }
  - pricing_config (only when audience_type = "product"):
    {
      "enabled": boolean,
      "model": string ("usage_based" | "waitlist" | "fixed"),
      "tiers": array of objects with "name", "price_per_unit" or "price_per_1k_tokens", "description"
    }
  Populate the correct one and set the other to null.
- Set framework_version to 'v4' and framework_creator to 'seldonframe' for all souls generated by this prompt.
- Output MUST be valid JSON only. No explanations, no markdown, no fences, no preamble.
- If you receive a follow-up message starting with ‘VALIDATION_ERROR:’, analyze the error, fix the JSON, and return ONLY the corrected JSON. No apology, no explanation.`;

function asRecord(value: unknown): Record<string, unknown> {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return {};
}

function readString(source: Record<string, unknown>, keys: string[], fallback = "") {
  for (const key of keys) {
    const value = source[key];
    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }
  }

  return fallback;
}

function readBoolean(source: Record<string, unknown>, keys: string[], fallback = false) {
  for (const key of keys) {
    const value = source[key];

    if (typeof value === "boolean") {
      return value;
    }

    if (typeof value === "string") {
      const normalized = value.trim().toLowerCase();
      if (normalized === "true") {
        return true;
      }
      if (normalized === "false") {
        return false;
      }
    }
  }

  return fallback;
}

function readStringArray(value: unknown) {
  if (!Array.isArray(value)) {
    return [] as string[];
  }

  return value
    .map((item) => {
      if (typeof item === "string") {
        return item.trim();
      }

      const record = asRecord(item);
      return readString(record, ["name", "title", "label", "id", "slug", "value", "text", "content"]);
    })
    .filter((item) => item.length > 0);
}

function normalizePipelineStages(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item) => {
      const record = asRecord(item);

      const name = readString(record, ["name", "stage_name", "title", "label"]);
      const description = readString(record, ["description", "stage_description", "details", "summary", "conversion_goal"]);

      return {
        name,
        description,
      };
    })
    .filter((stage) => stage.name.length > 0);
}

function normalizeIntakeFieldType(input: string) {
  const normalized = input.trim().toLowerCase();
  if (["text", "email", "select", "textarea", "number", "date", "checkbox"].includes(normalized)) {
    return normalized;
  }

  if (["long_text", "longtext", "paragraph", "multiline"].includes(normalized)) {
    return "textarea";
  }

  if (["integer", "float", "currency"].includes(normalized)) {
    return "number";
  }

  if (["bool", "boolean", "toggle"].includes(normalized)) {
    return "checkbox";
  }

  return "text";
}

function normalizeIntakeFormFields(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item, index) => {
      const record = asRecord(item);

      const label = readString(record, ["label", "field_name", "name", "question"], `Field ${index + 1}`);
      const fieldId = readString(record, ["field_id", "id", "key", "slug"], `field_${index + 1}`);
      const typeRaw = readString(record, ["type", "field_type", "input_type"], "text");
      const options = readStringArray(record.options ?? record.choices ?? record.values);

      return {
        field_id: fieldId,
        label,
        type: normalizeIntakeFieldType(typeRaw),
        required: readBoolean(record, ["required", "is_required", "mandatory"], false),
        options: options.length > 0 ? options : undefined,
        edge_case_note: readString(record, ["edge_case_note", "note", "help_text"], "") || undefined,
      };
    })
    .filter((field) => field.field_id.length > 0 && field.label.length > 0);
}

function normalizeLandingSections(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item) => {
      if (typeof item === "string") {
        return item.trim();
      }

      const record = asRecord(item);
      return readString(record, ["title", "name", "heading", "label", "content", "text"]);
    })
    .filter((section) => section.length > 0);
}

function normalizeIntelligenceHooks(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item) => {
      const record = asRecord(item);

      const triggerRaw = readString(record, ["trigger", "frequency", "cadence"], "weekly").toLowerCase();
      const formatRaw = readString(record, ["format", "value_format", "metric_type", "type"], "count").toLowerCase();

      const trigger = (["daily", "weekly", "monthly"] as const).includes(triggerRaw as "daily" | "weekly" | "monthly")
        ? (triggerRaw as "daily" | "weekly" | "monthly")
        : "weekly";

      const formatMap: Record<string, "percentage" | "currency" | "count" | "trend"> = {
        percent: "percentage",
        percentage: "percentage",
        currency: "currency",
        money: "currency",
        dollar: "currency",
        count: "count",
        number: "count",
        trend: "trend",
        timeseries: "trend",
      };

      const format = formatMap[formatRaw] ?? "count";
      const threshold = record.alert_threshold ?? record.threshold;

      return {
        metric: readString(record, ["metric", "hook_name", "name", "action"], "pipeline_health"),
        description: readString(record, ["description", "details", "summary", "action"], "Track this metric over time."),
        trigger,
        format,
        alert_threshold: typeof threshold === "string" ? threshold : null,
      };
    })
    .filter((hook) => hook.metric.length > 0);
}

function normalizeUcpCapabilities(value: unknown) {
  const record = asRecord(value);

  return {
    checkout: readBoolean(record, ["checkout", "payment_processing", "subscription_management"], false),
    booking: readBoolean(record, ["booking", "calendar_integration", "smart_scheduling"], false),
    catalog: readBoolean(record, ["catalog", "marketplace_support", "product_catalog"], false),
    cart: readBoolean(record, ["cart", "shopping_cart"], false),
  };
}

function normalizeCustomBlocks(value: unknown) {
  return readStringArray(value);
}

function normalizeAudienceType(input: string) {
  const normalized = input.trim().toLowerCase();
  return normalized === "product" ? "product" : "service";
}

function normalizeBaseFramework(input: string, audienceType: "service" | "product") {
  const normalized = input.trim().toLowerCase();

  if (audienceType === "service") {
    if (normalized === "agency" || normalized === "consulting") {
      return normalized;
    }

    return "coaching";
  }

  if (normalized === "f2-saas-launch") {
    return "f2-saas-launch";
  }

  return "f1-landing-waitlist";
}

function normalizePricingConfig(value: unknown) {
  if (value === null) {
    return null;
  }

  const record = asRecord(value);
  const tiers = Array.isArray(record.tiers)
    ? record.tiers
        .map((tier) => {
          const tierRecord = asRecord(tier);
          const pricePerUnit = tierRecord.price_per_unit;
          const pricePer1k = tierRecord.price_per_1k_tokens;

          return {
            name: readString(tierRecord, ["name", "title"], "Starter"),
            description: readString(tierRecord, ["description", "details"], ""),
            price_per_unit: typeof pricePerUnit === "number" ? pricePerUnit : undefined,
            price_per_1k_tokens: typeof pricePer1k === "number" ? pricePer1k : undefined,
          };
        })
        .filter((tier) => tier.name.length > 0)
    : [];

  const modelRaw = readString(record, ["model", "pricing_model"], "fixed").toLowerCase();
  const model = (["usage_based", "waitlist", "fixed"] as const).includes(modelRaw as "usage_based" | "waitlist" | "fixed")
    ? (modelRaw as "usage_based" | "waitlist" | "fixed")
    : "fixed";

  return {
    enabled: readBoolean(record, ["enabled", "is_enabled"], true),
    model,
    tiers,
  };
}

function normalizeBookingConfig(value: unknown) {
  if (value === null) {
    return null;
  }

  const record = asRecord(value);
  const services = Array.isArray(record.services)
    ? record.services
        .map((service) => {
          const serviceRecord = asRecord(service);
          const price = serviceRecord.price;

          return {
            name: readString(serviceRecord, ["name", "title"], "Service"),
            description: readString(serviceRecord, ["description", "details"], ""),
            price: typeof price === "number" ? price : 0,
          };
        })
        .filter((service) => service.name.length > 0)
    : [];

  const defaultDuration = record.default_duration_minutes;
  const bufferMinutes = record.buffer_minutes;

  return {
    enabled: readBoolean(record, ["enabled", "is_enabled"], true),
    default_duration_minutes: typeof defaultDuration === "number" ? defaultDuration : 30,
    buffer_minutes: typeof bufferMinutes === "number" ? bufferMinutes : 10,
    services,
  };
}

function normalizeSoulOutput(raw: unknown) {
  const input = asRecord(raw);
  const audienceType = normalizeAudienceType(readString(input, ["audience_type"], "service"));
  const baseFramework = normalizeBaseFramework(readString(input, ["base_framework"], ""), audienceType);
  const bookingConfig = normalizeBookingConfig(input.booking_config);
  const pricingConfig = normalizePricingConfig(input.pricing_config);

  return {
    business_name: readString(input, ["business_name", "name"], "Untitled Business"),
    audience_type: audienceType,
    base_framework: baseFramework,
    tagline: readString(input, ["tagline"], ""),
    soul_description: readString(input, ["soul_description", "description"], ""),
    pipeline_stages: normalizePipelineStages(input.pipeline_stages),
    intake_form_fields: normalizeIntakeFormFields(input.intake_form_fields),
    booking_config: audienceType === "service" ? bookingConfig : null,
    pricing_config: audienceType === "product" ? pricingConfig : null,
    landing_page_sections: normalizeLandingSections(input.landing_page_sections),
    intelligence_hooks: normalizeIntelligenceHooks(input.intelligence_hooks),
    ucp_capabilities: normalizeUcpCapabilities(input.ucp_capabilities),
    custom_blocks: normalizeCustomBlocks(input.custom_blocks),
    split_recommendation: readBoolean(input, ["split_recommendation"], false),
    custom_domain_suggestion:
      typeof input.custom_domain_suggestion === "string" ? input.custom_domain_suggestion : input.custom_domain_suggestion === null ? null : null,
    framework_version: readString(input, ["framework_version"], "v4"),
    framework_creator: typeof input.framework_creator === "string" ? input.framework_creator : "seldonframe",
  };
}

export const routingSystemPrompt = `${soulCompilerSystemPrompt}

For this call, return ONLY routing JSON in this exact shape:
{
  "audience_type": "service" | "product",
  "base_framework": "coaching" | "agency" | "consulting" | "f1-landing-waitlist" | "f2-saas-launch",
  "business_name": "string",
  "tagline": "string",
  "split_recommendation": boolean
}`;

export type SoulCompileInput = {
  inputTextOrScrapedContent: string;
  client: Anthropic;
  model?: string;
};

export type SoulCompileResult = {
  routing: RoutingResult;
  soul: SoulV4;
  attempts: 1 | 2;
  raw: {
    routingText: string;
    extractionText: string;
    retryText?: string;
  };
};

export function createByokAnthropicClient(apiKey: string) {
  const normalized = apiKey.trim();
  if (!normalized) {
    throw new Error("Missing Claude API key");
  }

  return new Anthropic({ apiKey: normalized });
}

export function getByokClaudeKeyFromHeaders(headers: Headers) {
  const candidates = [
    headers.get("x-claude-api-key"),
    headers.get("anthropic-api-key"),
    headers.get("x-anthropic-api-key"),
    headers.get("x-api-key"),
  ];

  const key = candidates.find((value) => typeof value === "string" && value.trim().length > 0);
  return key?.trim() || "";
}

function extractText(content: Array<{ type: string; text?: string }>) {
  return content
    .map((part) => (part.type === "text" ? part.text ?? "" : ""))
    .join("\n")
    .trim();
}

function extractFirstJsonObject(input: string) {
  const fenced = input.match(/```json\s*([\s\S]*?)```/i) ?? input.match(/```\s*([\s\S]*?)```/i);
  const candidate = fenced?.[1]?.trim() ?? input.trim();

  try {
    return JSON.parse(candidate);
  } catch {
    const start = candidate.indexOf("{");
    const end = candidate.lastIndexOf("}");

    if (start >= 0 && end > start) {
      try {
        return JSON.parse(candidate.slice(start, end + 1));
      } catch {
        return null;
      }
    }

    return null;
  }
}

function zodErrorToValidationMessage(error: ZodError) {
  const details = error.issues.map((issue) => {
    const path = issue.path.length > 0 ? issue.path.join(".") : "root";
    return `${path}: ${issue.message}`;
  });

  return details.join("; ");
}

export async function runRoutingCall(params: {
  client: Anthropic;
  inputTextOrScrapedContent: string;
  model?: string;
}) {
  const response = await params.client.messages.create({
    model: params.model || DEFAULT_MODEL,
    max_tokens: ROUTING_MAX_TOKENS,
    system: routingSystemPrompt,
    messages: [
      {
        role: "user",
        content: `Business input: ${params.inputTextOrScrapedContent}\n\nDetect audience, choose closest base framework, customize for every specific edge case mentioned. Output ONLY the JSON above.`,
      },
    ],
  });

  const text = extractText(response.content as Array<{ type: string; text?: string }>);
  const parsed = extractFirstJsonObject(text);

  const validated = routingResultSchema.safeParse(parsed);
  if (!validated.success) {
    throw new Error(`Routing validation failed: ${zodErrorToValidationMessage(validated.error)}`);
  }

  return {
    routing: validated.data,
    text,
  };
}

async function runExtractionCall(params: {
  client: Anthropic;
  inputTextOrScrapedContent: string;
  routing: RoutingResult;
  model?: string;
  validationErrorPrefix?: string;
}) {
  const validationPrefix = params.validationErrorPrefix?.trim();

  const response = await params.client.messages.create({
    model: params.model || DEFAULT_MODEL,
    max_tokens: EXTRACTION_MAX_TOKENS,
    system: soulCompilerSystemPrompt,
    messages: [
      {
        role: "user",
        content: `${validationPrefix ? `VALIDATION_ERROR: ${validationPrefix}\n\n` : ""}Business input: ${params.inputTextOrScrapedContent}\n\nRouting context from call 1:\n${JSON.stringify(
          params.routing
        )}\n\nDetect audience, choose closest base framework, customize for every specific edge case mentioned. Output ONLY valid JSON matching the locked schema. Make it production-ready for immediate workspace creation.`,
      },
    ],
  });

  const text = extractText(response.content as Array<{ type: string; text?: string }>);
  const parsed = extractFirstJsonObject(text);
  const normalized = normalizeSoulOutput(parsed);
  const validated = soulV4Schema.safeParse(normalized);

  return {
    text,
    parsed: normalized,
    validated,
  };
}

export async function compileSoulWithTwoCallPattern(input: SoulCompileInput): Promise<SoulCompileResult> {
  const source = input.inputTextOrScrapedContent.trim();
  if (!source) {
    throw new Error("inputTextOrScrapedContent is required");
  }

  const routingResult = await runRoutingCall({
    client: input.client,
    inputTextOrScrapedContent: source,
    model: input.model,
  });

  const firstAttempt = await runExtractionCall({
    client: input.client,
    inputTextOrScrapedContent: source,
    routing: routingResult.routing,
    model: input.model,
  });

  if (firstAttempt.validated.success) {
    return {
      routing: routingResult.routing,
      soul: firstAttempt.validated.data,
      attempts: 1,
      raw: {
        routingText: routingResult.text,
        extractionText: firstAttempt.text,
      },
    };
  }

  const retryReason = zodErrorToValidationMessage(firstAttempt.validated.error);
  const retryAttempt = await runExtractionCall({
    client: input.client,
    inputTextOrScrapedContent: source,
    routing: routingResult.routing,
    model: input.model,
    validationErrorPrefix: retryReason,
  });

  if (!retryAttempt.validated.success) {
    throw new Error(`Soul validation failed after retry: ${zodErrorToValidationMessage(retryAttempt.validated.error)}`);
  }

  return {
    routing: routingResult.routing,
    soul: retryAttempt.validated.data,
    attempts: 2,
    raw: {
      routingText: routingResult.text,
      extractionText: firstAttempt.text,
      retryText: retryAttempt.text,
    },
  };
}
